Ruiners
dkotegov/homework-4 pull request #108
Opened 2021-04-14 21:52 UTC by ErikDoter

2021-04-15 16:32 UTC, ErikDoter commented
Все вроде ок

2021-04-15 16:34 UTC, ErikDoter reviewed
Все вроде ок

2021-04-15 17:46 UTC, Arkadiyche commented
ок

2021-05-13 15:55 UTC, dkotegov requested changes

2021-05-13 15:55 UTC, dkotegov commented on Pages/search_page.py
> +        elem = self.ELEMENT_USER + string + '")]'
Этот селектор будет очень нестабильным

2021-05-13 15:55 UTC, dkotegov commented on Pages/settings_page.py
> +        self.set_username("1234")
Значения должны быть в тесте

2021-05-13 15:55 UTC, dkotegov commented on tests/auth_tests.py
> +        auth_page.auth_wrong("xmksamxsmlksa", password)
В тесте нет ассертов

2021-05-13 15:55 UTC, dkotegov commented on tests/auth_tests.py
> +        auth_page.auth()
В этом тесте ничего не проверяется

2021-05-13 15:55 UTC, dkotegov commented on tests/auth_tests.py
> +        auth_page.logout()
И тут

2021-05-13 15:55 UTC, dkotegov commented on tests/comment_test.py
> +        film_page.open()
Копипаста, это можно унести в setup

2021-05-13 15:55 UTC, dkotegov commented on tests/comment_test.py
> +        self.assertEqual(check, True)
assertTrue(check)

2021-05-13 15:55 UTC, dkotegov commented on tests/playlist_tests.py
> +        self.assertEqual(before == after, True)
assertEqual(before, after)

2021-05-13 15:55 UTC, dkotegov commented on tests/playlist_tests.py
> +        profile_page = ProfilePage(self.driver)
Это нужно унести в setup

2021-05-13 15:55 UTC, dkotegov commented on tests/playlist_tests.py
> +        profile_page.delete_playlist()
а это в teardown

2021-05-13 15:55 UTC, dkotegov commented on tests/playlist_tests.py
> +        after = profile_page.get_count_playlist()
Тут надо проверить сообщение об ошибке

2021-05-13 15:55 UTC, dkotegov commented on tests/playlist_tests.py
> +        profile_page.delete_playlist()
И тут

2021-05-13 15:55 UTC, dkotegov commented on tests/playlist_tests.py
> +        self.assertEqual(check, True)
И тут

2021-05-13 15:55 UTC, dkotegov commented on tests/rating_tests.py
> +        film_page.check_succes()
А где ассерты?

2021-05-13 15:55 UTC, dkotegov commented on tests/search_tests.py
> +        string = "Корпорация монстров"
Константы можно вынести

2021-05-13 15:55 UTC, dkotegov commented on tests/search_tests.py
> +        self.assertEqual(check, True)
assertTrue(check)

2021-05-13 15:55 UTC, dkotegov commented on tests/setting_test.py
> +        setting_page.change_pass(new_pass, setting_page.PASSWORD_INPUT, setting_page.PASSWORD_INPUT)
Где ассерты?

2021-05-13 15:55 UTC, dkotegov commented on tests/setting_test.py
> +        setting_page.change_pass(setting_page.PASSWORD_INPUT, new_pass, new_pass)
Эта строчка сломает другие тесты при паралельном запуске

2021-05-13 15:55 UTC, dkotegov commented on tests/setting_test.py
> +        WebDriverWait(self.driver, 5).until(EC.presence_of_element_located((By.XPATH, setting_page.ERROR_WRONG_OLD)))
Ассерты?

2021-05-13 15:55 UTC, dkotegov commented on tests/setting_test.py
> +        new_pass = "new_password"
Это константа

2021-05-13 15:55 UTC, dkotegov commented on tests/setting_test.py
> +        check = profile_page.check_username(new_username)
Проверки должны быть в тестах, а не пейджах

2021-05-13 15:55 UTC, dkotegov commented on tests/signup_tests.py
> +        login = signup_page.SIGNUP_LOGIN
Это сломает повторный запуск

2021-05-13 15:55 UTC, dkotegov commented on tests/signup_tests.py
> +        signup_page.signup_wrong(login, "12345678", "qwer@mail.ru")
Ассерты должны быть в тестах

2021-05-13 15:55 UTC, dkotegov commented on tests/subscribe_tests.py
> +        people_page.unsubscribe()
Если какая-то из строчек выше упадет, то эта строчка не выполнится, поэтому это должно быть в teardown

2021-06-05 15:18 UTC, ErikDoter commented
Теперь точно ок

2021-06-05 15:18 UTC, Arkadiyche commented
OK

2021-06-16 11:15 UTC, dkotegov commented
Принято

2021-06-16 11:15 UTC, closed without merging