ExtraCoders
dkotegov/homework-4 pull request #112
Opened 2021-04-15 20:29 UTC by marksadykov

2021-04-15 20:32 UTC, Dellvin commented
Аппрув!

2021-04-15 20:34 UTC, SmailD35 commented
Аппрув

2021-04-15 20:44 UTC, marksadykov commented
Аппрув

2021-05-13 16:55 UTC, dkotegov commented
Вся работа с браузером должна быть в PageObject
В тестах должны быть ассерты
Копипасту надо вынести в setUp и tearDown

2021-05-13 16:57 UTC, dkotegov requested changes
Вся работа с браузером должна быть в PageObject
В тестах должны быть ассерты
Копипасту надо вынести в setUp и tearDown

2021-10-14 13:21 UTC, closed without merging