YSNP.KOYA
dkotegov/homework-4 pull request #116
Opened 2021-10-31 22:35 UTC by alSergey

2021-10-31 23:38 UTC, alSergey commented on components/product_card.py
> +        return index
Функция не всегда срабатывает. Иногда лайк не ставится

2021-10-31 23:38 UTC, alSergey commented on pages/__init__.py
> +from .promotion import PromotionPage
Не хватает пустой строчки

2021-10-31 23:38 UTC, alSergey commented on .gitignore
> +.idea
Не хватает пустой строчки

2021-10-31 23:38 UTC, alSergey commented on pages/edit_product.py
> +    PATH = "product/198/edit"
Какие-то рандомные цифры у урлах. Надо подумать, может их куда-то вынести как константы

2021-10-31 23:38 UTC, alSergey commented on pages/product.py
> +        self.helpers.wait(until=EC.presence_of_element_located((By.CSS_SELECTOR, self.SLIDER_SELECTED_IMG)))
В get_element уже есть wait

2021-10-31 23:38 UTC, alSergey commented on pages/product.py
> +        self.helpers.wait(until=EC.presence_of_element_located((By.CSS_SELECTOR, self.PREVIEW)))
В get_element уже есть wait

2021-10-31 23:38 UTC, alSergey commented on pages/product.py
> +        self.helpers.wait(until=EC.element_to_be_clickable((By.CSS_SELECTOR, self.SLIDER_IMG)))
В get_elements уже есть wait

2021-10-31 23:38 UTC, alSergey commented on pages/product.py
> +        self.helpers.wait(until=EC.presence_of_element_located((By.CSS_SELECTOR, self.PHONE)))
В get_element уже есть wait

2021-10-31 23:38 UTC, alSergey commented on tests/create_product_test.py
> +        test2 = "ffsdfvgsdv fh bcvb g dg gb gfxdfg fxdfbffsdfvgsdv fh bcvb g dg gb gfxdfg fxdfbffsdfvgsdv fh bcvb g " \
Мне кажется это достаточно длинное название, чтобы поместить его в файл

2021-10-31 23:38 UTC, alSergey commented on pages/product.py
> +    SLIDER_SELECTED_IMG = '.slider-carousel img[style = \'padding-top: 1vh; padding-bottom: 1vh; opacity: 1;\']'
Мне кажется это слишком сложный селектор. Может быть его как-то упростить?

2021-10-31 23:38 UTC, alSergey commented on tests/product_test.py
> +            "Появился не номер телефона")
Вот это не понятный тест. Откуда взялся этот regex

2021-10-31 23:38 UTC, alSergey commented on tests/product_test.py
> +        self.product.change_path("103")
Почему ты тут 2 раза меняешь path? Давай все константы в начале тестов объявлять, а потом использовать

2021-10-31 23:38 UTC, alSergey commented on tests/product_test.py
> +        user_products_page.product_card.click_product()
Функция click_product возвращает product_id. Можно его использовать, а не брать из урла

2021-10-31 23:38 UTC, alSergey commented on tests/seller_side_bar_test.py
> +        user_id = "1"
Надо константы вынести в отдельный класс

2021-10-31 23:38 UTC, alSergey commented on tests/settings_test.py
> +        self.assertEqual(self.settings.pwd_form.get_pwd_change_error(), '', "Нет ошибки")
Может быть сделать функцию is_error

2021-10-31 23:38 UTC, alSergey commented on tests/user_favorites_test.py
> +        self.favorites.favorite_products.remove_like_product(0)
Нужно снимать лайк с того продукта, на который ты ставил лайк. Откуда ты знаешь, что ты поставил лайк на 0 товар?

2021-10-31 23:38 UTC, alSergey commented on tests/user_favorites_test.py
> +        self.favorites.favorite_products.remove_like_product(0)
Нужно снимать лайк с того продукта, на который ты ставил лайк. Не факт, что ты лайкнул 1 товар

2021-10-31 23:38 UTC, alSergey commented on components/product_card.py
> +    def like_product(self):
Можно подумать, чтобы функция возвращала не index, а product_id. И работать везде с product_id. Это надежнее, чем работа по индексу

2021-10-31 23:54 UTC, alSergey commented on pages/reviews.py
> +        return user_url
Мне кажется значение лучше рандомить. Ты же тестируешь, что для любого элемента будет работать твоя логика. Сейчас это выглядит так, что это будет работать только для 0 элемента

2021-10-31 23:54 UTC, alSergey commented on pages/user_messages.py
> +        self.helpers.get_elements(self.MESSAGE_CARD)[0].click()
Мне кажется значение лучше рандомить. Ты же тестируешь, что для любого элемента будет работать твоя логика. Сейчас это выглядит так, что это будет работать только для 0 элемента

2021-11-01 08:50 UTC, IvanGorshkov reviewed
private метод обозначается, как def __method

2021-11-01 08:50 UTC, IvanGorshkov commented on components/header.py
> +        self.helpers.click_button(self.LOGO)
Здесь разве нужен wait? он в click_button есть

2021-11-01 08:50 UTC, IvanGorshkov commented on components/login.py
> +
Может это вынести в отдельный helper?

2021-11-01 08:50 UTC, IvanGorshkov commented on helpers/helpers.py
> +        return self.driver.find_elements(by, selector)
я погуглил. Если нужно сделать атрибут private, то нужно два нижних подчеркивания в начале

2021-11-01 08:50 UTC, IvanGorshkov commented on pages/registration.py
> +        return self.helpers.is_contains(self.REGISTRATION_ERROR)
wait можно убрать

2021-11-01 08:50 UTC, IvanGorshkov commented on pages/user_messages.py
> +        return self.helpers.get_element(self.TITLE) is not None
self.helpers.get_element уже есть wait

2021-11-01 08:52 UTC, alSergey commented on components/header.py
> +        self.helpers.click_button(self.LOGO)
В Firefox не проходил тест. У нас в click_button немного другой wait стоит, добавил дополнительно

2021-11-01 08:53 UTC, alSergey commented on components/login.py
> +
Можно, но зачем? Это разовое решение, потому что только в этом месте обычный click не работал. не думаю что есть смысл выносить

2021-11-01 09:54 UTC, IvanGorshkov commented on components/header.py
> +        self.helpers.click_button(self.LOGO)
может тогда в click_button логику поменять? кнопка как раз должна ожидать element_to_be_clickable, а сейчас presence_of_element_located

2021-11-01 12:09 UTC, alSergey commented
Аппрув

2021-11-01 12:09 UTC, IvanGorshkov commented
Аппрув

2021-11-01 12:10 UTC, VVaria commented
аппрув

2021-11-01 12:10 UTC, dantedoyl commented
Аппрув

2021-11-05 20:16 UTC, Betchika99 requested changes
Общие замечания
- [ ] Очищать ресурсы тестов, возвращать в исходное состояние (например, это касается авторизации, сортировок в поиске)
- [ ] Более осмысленные названия для тестов
- [ ] Убрать ненужные циклы while continue
- [ ] Замечания для `footer_test` аналогичные как для `header_test `. В целом посмотрите замечания по всему проекту, потому что я могла что-то пропустить и не везде указывала повторяющиеся ошибки
- [ ] Проверить все методы, которые семантически ошибочны (например click_button должен только кликать и не возвращать ничего), все методы должны быть чистыми
- [ ] Не увидела тесты на переходы на страницы проекта (все страницы открываются по ссылке через метод `open()`, а интерфейсные переходы не протестированы)
- [ ] добавить **больше функциональных тестов**, а не только переходов. Проверяйте в том числе позитивные кейсы, иначе как вы поймете, что вас проект работает корректно?
- [ ] не объединять разные тесты в один

2021-11-05 20:16 UTC, Betchika99 commented on README.md
> +```
эти команды нужны для третьего терминала, лучше перенести их ниже

2021-11-05 20:16 UTC, Betchika99 commented on README.md
> +./grid.sh
у меня так не запустилось, сработало только `zsh grid.sh`

2021-11-05 20:16 UTC, Betchika99 commented on components/header.py
> +    AD = DROPDOWN_ITEM.format("Мои объявления")
не очень понятное название для переменной

2021-11-05 20:16 UTC, Betchika99 commented on helpers/test.py
> +        # self.driver = webdriver.Chrome(executable_path="../chromedriver")
давайте уберем комментарии, где они не нужны

2021-11-05 20:16 UTC, Betchika99 commented on pages/product.py
> +    PATH = "product/48"
обычно путь начинается со / . Не ошибка, но семантически не очень верно

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +    def testFirstImgSrcEqualPreview(self):
часть "Src" можно удалить, потому что и так понятно

2021-11-05 20:16 UTC, Betchika99 commented on pages/product.py
> +    SLIDER_SELECTED_IMG = '.slider-carousel img[style = \'padding-top: 1vh; padding-bottom: 1vh; opacity: 1;\']'
выглядит, как костыль :( здесь лучше убрать часть со style, и подумать, как взять первый img из слайдера

2021-11-05 20:16 UTC, Betchika99 commented on pages/product.py
> +    SLIDER_SELECTED_IMG = '.slider-carousel img[style = \'padding-top: 1vh; padding-bottom: 1vh; opacity: 1;\']'
разные кавычки в проекте = один грустный котик

2021-11-05 20:16 UTC, Betchika99 commented on pages/product.py
> +        images[randrange(len(images))].click()
теоретически здесь может произойти клик на картинку, которая уже открыта. Тогда тест будет некорректный

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +            self.product.photos.preview_img_src(),
лучше вот эти два значения вынести в переменные, чтобы запись была более читаемая. Здесь и далее

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +    def testOpenAllItemsBySellerName(self):
лучше название сделать более осмысленным и приближенным к описанию, например `testRedirectToAdsByClickSellerName`

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +        seller_products = SellerProductsPage(driver=self.driver)
лучше `seller_products_page`

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +        seller_products = SellerProductsPage(driver=self.driver)
а создание этой страницы нельзя вынести в setUp? она создаётся в нескольких местах, но при этом никакой модификации над ней нет => можно оптимизировать

2021-11-05 20:16 UTC, Betchika99 commented on helpers/helpers.py
> +    def click_button(self, selector, by=SELECTOR.CSS):
не очень понятно, почему это button. Ты же можешь кликнуть на любой элемент на странице (ссылка, текст, меню и т.п.). Лучше обобщеннее назвать кмк

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +        self.product.info_card.click_on_seller_name()
есть ощущение, что на каком-нибудь медленном интернете здесь может мигнуть тест, потому что урл сразу не поменяется. Возможно, есть смысл здесь после клика еще подождать появления какого-то характерного элемента для новой страницы, чтобы убедиться, что переход действительно произошел

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +        self.assertTrue(seller_products.is_compare_url(url), "Ошибка редиректа на страницу всех объявлений")
`is_compare_url` больше похожа на общий хелпер для сравнения двух урлов, а не на метод страницы. Можно также попробовать заменить assertTrue на assertEqual и сразу сравнивать два урла

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +    def tesToShowPhoneAuth(self):
test - опечатка

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +        self.assertRegex(
а почему здесь не проверять на конкретный номер? Вы же хардкодите урлы, смотрите конкретный продукт с конкретным продавцом, а у него конкретный номер

2021-11-05 20:16 UTC, Betchika99 commented on pages/product.py
> +            continue
а зачем нужен этот цикл? почему не убрать?

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +    def testFailToRedirectMasNotAuth(self):
а причем тут редирект? Нужно более осмысленное название, что нельзя написать сообщение. Упрощаем :)

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +        self.product.login.auth()
а разлогиниться? после каждого теста надо возвращать состояние сайта в исходное

2021-11-05 20:16 UTC, Betchika99 commented on tests/product_test.py
> +    def testToRedirectMasAuth(self):
testRedirectToMsgByClickWriteMsgBtn - более понятное название. Или хотя бы в общем придерживаться более лаконичного названия

2021-11-05 20:16 UTC, Betchika99 commented on components/product_card.py
> +    LIKED = ".product-card__like_liked"
а зачем дублировать два одинаковых селектора?

2021-11-05 20:16 UTC, Betchika99 commented on components/product_card.py
> +        return product_id
выглядит нелогичным возвращать айди продукта здесь. Это же метод, который просто кликает. Он семантически не должен ничего возвращать

2021-11-05 20:16 UTC, Betchika99 commented on components/product_card.py
> +    def click_product(self):
есть ощущение, что здесь лучше принимать аргументом айди продукта, на который нужно кликнуть. Вычислять его вне этого метода и просто передавать. Будет более изолированно и будет больше подходить под это название. 
Аналогично с другими методами в этом файле

2021-11-05 20:16 UTC, Betchika99 commented on tests/seller_products_test.py
> +        product_id = self.seller_products.product_card.click_product()
здесь тоже есть ощущение, что нужно подождать, пока страница поменяется на другую (см. коммент к `tests/product_test.py`)

2021-11-05 20:16 UTC, Betchika99 commented on tests/seller_products_test.py
> +        self.assertFalse(self.seller_products.product_card.check_remove_like_product(index), "Не удалось убрать лайк")
это два разных теста - на установку лайка и снятие лайка. Так же, как у вас в чеклисте было

2021-11-05 20:16 UTC, Betchika99 commented on tests/seller_products_test.py
> +        self.seller_products.login.click_close()
не очень понятно, зачем это проверять ассертом. Кажется, что правильнее дождаться попап авторизации и авторизоваться

2021-11-05 20:16 UTC, Betchika99 commented on components/product_card.py
> +        return self.helpers.is_element_contains_class(liked, self.PRODUCT_LIKED)
не очень понятно, где проверка собственно, что именно конкретный продукт лайкнут, а не просто рандомный. Если я пролайкаю несколько, то здесь проверится только первый, а мне, к примеру, нужен третий. И это будет не валидный тест

2021-11-05 20:16 UTC, Betchika99 commented on tests/search_test.py
> +    def testInputAmount(self):
не очень понятно, о чем тест

2021-11-05 20:16 UTC, Betchika99 commented on pages/search.py
> +        self.helpers.input_value(self.TO_A, text)
не очень понятно, почему вставляется одно и то же значение. Кажется, что должно быть два аргумента - А и В

2021-11-05 20:16 UTC, Betchika99 commented on pages/search.py
> +        return from_a.get_attribute('value'), to_a.get_attribute('value')
а зачем что-то возвращать здесь? в качестве геттера должен быть другой метод. семантически здесь только ввод значений и всё, возврата не ожидается

2021-11-05 20:16 UTC, Betchika99 commented on tests/search_test.py
> +        self.assertTupleEqual(expected_3, res_bad, "Некорректный результат")
выглядят, как три разных теста (как в чеклистах)

2021-11-05 20:16 UTC, Betchika99 commented on tests/search_test.py
> +        self.assertTupleEqual(expected_3, res_bad, "Некорректный результат")
а в чем здесь проверка? можно же ввести число > 10 символов, т.е. тест аналогичен 1му случаю

2021-11-05 20:16 UTC, Betchika99 commented on pages/search.py
> +            time.sleep(0.06)  # Самодельный wait. Ждём пока лента обновится
sleep - это антипаттерн. Нужно придумать решение с wait, если нужно именно это. Здесь и далее

2021-11-05 20:16 UTC, Betchika99 commented on pages/search.py
> +        self.search_products.save_products_amount()
а почему здесь сохраняем цену? а потом проверяем на имена...

2021-11-05 20:16 UTC, Betchika99 commented on utils/sort.py
> +    list_not_sorted = []
эта переменная выглядит лишней, т.к. функция и так принимает в себя несортированный список products. И не очень понятно, зачем возвращать это же значение из функции

2021-11-05 20:16 UTC, Betchika99 commented on utils/sort.py
> +    list_sorted = natural_sort(list_sorted)
можно заменить на более короткую запись `natural_sort(list(map(lambda x: x.text, products)))`

2021-11-05 20:16 UTC, Betchika99 commented on pages/search.py
> +        self.search_products.save_products_amount()
и зачем это?

2021-11-05 20:16 UTC, Betchika99 commented on tests/search_test.py
> +class SearchTest(Test):
во всех тестах не хватает сброса в дефолтное значение (особенно касательно сортировок). Нужно, чтобы тесты были чистыми

2021-11-05 20:16 UTC, Betchika99 commented on tests/search_test.py
> +        self.assertFalse(self.search.search_products.check_remove_like_product(index), "Не удалось убрать лайк")
выглядят как два разных теста - поставить лайк и убрать лайк

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_products_test.py
> +        self.user_products.open()
кажется, что это лучше унести из setUp, потому что в тестах оно не везде нужно сразу и где-то повторяется

2021-11-05 20:16 UTC, Betchika99 commented on tests/header_test.py
> +        """Проверка, что при нажатии на логотип открывается главная страница"""
в этом тесте для начала надо наверно на какую-то другую страницу перейти. иначе мы находимся на главной и проверяем, что перешли на главную - плохая проверка

2021-11-05 20:16 UTC, Betchika99 commented on tests/header_test.py
> +        self.assertTrue(self.main.header.is_opened_dropdown(), "Не открылся дропдаун")
пожалуй, здесь не нужен отдельный ассерт. Достаточно будет просто wait до открытия дропдауна. Здесь и далее

2021-11-05 20:16 UTC, Betchika99 commented on tests/header_test.py
> +        user_id = os.environ.get("USER_ID")
а зачем выносить это поле в энв, если в остальных случаях вы хардкодите? кажется, тут тоже можно захардкодить просто, это же не приватная инфа

2021-11-05 20:16 UTC, Betchika99 commented on tests/theme_test.py
> +        self.assertNotEqual(theme_1, theme_2, "Одинаковые темы")
1) выглядят, как разные тесты, т.к. проверяются разные кейсы
2) почему проверяете на то, что темы разные, а не на то, что тема поменялась на ту, на которую мы хотели? нефункциональная проверка получается

2021-11-05 20:16 UTC, Betchika99 commented on tests/registration_test.py
> +        self.assertTrue(self.registration.form.is_error_name(), "Нет ошибки")
не особо понятно, зачем выносить это в отдельный метод. Лучше перенести в сам тест, чтобы было понятнее. Аналогично и с другими полями

2021-11-05 20:16 UTC, Betchika99 commented on tests/registration_test.py
> +        self.__test_name__(test2)
это два разных теста. Аналогично и с другими кейсами

2021-11-05 20:16 UTC, Betchika99 commented on tests/registration_test.py
> +    def testErrorTelephoneInput(self):
телефон не проверяется на соответствие формату телефона? что начинается с 8 или +7, к примеру

2021-11-05 20:16 UTC, Betchika99 commented on tests/registration_test.py
> +        self.assertTrue(self.registration.form.is_error(), "Нет ошибки")
в этом файле не хватает позитивных историй. Нужно проверять не только негативные

2021-11-05 20:16 UTC, Betchika99 commented on pages/registration.py
> +    def is_error(self):
название не очень понятное, лучше более информативно назвать

2021-11-05 20:16 UTC, Betchika99 commented on tests/login_test.py
> +        self.assertFalse(self.main.login.is_opened(), "Не закрылась авторизация")
этот тест лишний, т.к. вы все равно в каждом тесте открываете этот попап. Разве что только закрытие проверить

2021-11-05 20:16 UTC, Betchika99 commented on tests/login_test.py
> +        # Не понятно как проверять ошибку. У нас по submit вылезает стандартная браузерная ошибка
можно проверить, что поле заполнено неверно (псевдокласс инпута `invalid`). Посмотрите в гугле об этом поподробнее, вот [пример](https://stackoverflow.com/questions/9178122/how-to-check-if-an-html5-validation-was-triggered-using-selenium)

2021-11-05 20:16 UTC, Betchika99 commented on components/login.py
> +    LOGIN = ".auth-content-form__tel"
но это же не логин, это телефон...

2021-11-05 20:16 UTC, Betchika99 commented on tests/main_test.py
> +        self.assertTrue(search.is_compare_url(url), "Не открылась страница поиска")
этот тест избыточен, потому что ниже в других тестах это проверяется

2021-11-05 20:16 UTC, Betchika99 commented on tests/main_test.py
> +        self.assertTrue(search.is_compare_url(url), "Не открылась страница поиска")
этот тест избыточен, потому что ниже в других тестах это проверяется

2021-11-05 20:16 UTC, Betchika99 commented on tests/main_test.py
> +        self.assertFalse(self.main.product_card.check_remove_like_product(index), "Не удалось убрать лайк")
два разных теста

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_messages_test.py
> +        self.messages.open()
лучше перенести это внутрь тех тестов, где это нужно. Потому что в некоторых случаях страницу нужно открывать только после авторизации

2021-11-05 20:16 UTC, Betchika99 commented on pages/user_messages.py
> +        return product_url
клик - это просто клик :) не нужно ничего возвращать из этой функции. Лучше управлять получением каких-то данных извне или в другом методе. Здесь и в других подобных методах нужно поправить

2021-11-05 20:16 UTC, Betchika99 commented on pages/user_messages.py
> +        self.helpers.get_elements(self.MESSAGE_CARD)[0].click()
а почему не использовать просто `get_element` и сразу с одним элементом работать?

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_messages_test.py
> +        self.messages.open()
перезагрузка выглядит здесь как грязный хак. Лучше дождаться с помощью wait, что сообщение появилось в списке

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_messages_test.py
> +        self.assertEqual(before_send + 1, after_send, "Количество сообщений не изменилось")
на самом деле не очень корректная проверка. Если (когда) у вас появится пагинация списка сообщений и в чате будет очень много сообщений, то этот тест ничего не покажет и просто упадет. Лучше отправлять каждый раз уникальное сообщение и проверять его содержимое в блоке отправленных сообщений. Так вы проверите целиком эту функциональность

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_messages_test.py
> +        self.assertTrue(self.messages.chats_block.is_chat_opened(), "Не открылся чат пользователя")
это избыточный тест, он проверяется в тестах выше

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_reviews_test.py
> +        """Заголовок отзыва. Переход на страницу товара при нажатии на название"""
какое-то ложное описание

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_reviews_test.py
> +        self.reviews.review_block.set_sort_by_date()
у вас на странице, насколько я вижу, сортировка по дате - по умолчанию. Поэтому здесь как-то иначе надо проверять, более функционально

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_reviews_test.py
> +        """Панель отзывов - заголовок. Сортировка по дате создания при нажатии кнопки сортировать по дате"""
ложное описание :(

2021-11-05 20:16 UTC, Betchika99 commented on pages/reviews.py
> +            count2 = stars[i].find_elements(By.CSS_SELECTOR, self.STAR_ACTIVE)
вы же два одинаковых отзыва проверяете, в чем смысл проверки?

2021-11-05 20:16 UTC, Betchika99 commented on pages/user_await_reviews.py
> +        self.helpers.get_elements(self.REVIEW_CARD)[0].click()
почему не использовать `get_element` и работать сразу с одним элементом?

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_await_reviews_test.py
> +        self.assertTrue(self.await_reviews.review_popup.is_popup_opened(), "Не открылся попап")
не нужно проверять, т.к. это проверяется внутри других тестов здесь

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_await_reviews_test.py
> +        before_click = self.await_reviews.await_review_block.count_cards()
лучше дать более осмысленное название переменной

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_await_reviews_test.py
> +        self.assertEqual(before_click, self.await_reviews.await_review_block.count_cards(), "Товар пропал")
мы же на юзеров отзыв оставляем, а не на товар..

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_await_reviews_test.py
> +        self.assertTrue(self.await_reviews.review_popup.is_error(), "Нет ошибки")
в этом файле чаще используется авторизация => ее лучше вынести в setUp. А там, где она не нужна, просто сбросьте авторизацию

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_await_reviews_test.py
> +        self.assertTrue(self.await_reviews.review_popup.is_error(), "Нет ошибки")
а почему вы тут не проверяется собственно само оставление отзыва (позитивный сценарий)?

2021-11-05 20:16 UTC, Betchika99 commented on components/review_popup.py
> +    def is_error(self):
лучше более осмысленно назвать

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_favorites_test.py
> +        self.favorites.open()
кажется, эта часть здесь лишняя. Мы же не лайки проверяем

2021-11-05 20:16 UTC, Betchika99 commented on components/product_card.py
> +    PRODUCTS = ".product-card"
у вас внутри этого селектора еще лежит куча всяких других селекторов (например, лайк). Потенциально здесь может возникнуть проблема при клике (селениум кликнет на карточку, но попадет на лайк). Поэтому кмк лучше взять селектор поглубже, чтобы он ни с чем не конфликтовал, а тест не мигал

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_favorites_test.py
> +        self.favorites.open()
перезагрузка выглядит как грязный хак. Лучше подождать, пока элемент пропадет

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_side_bar_test.py
> +        settings = UserSettingsPage(driver=self.driver)
зачем еще раз создавать, если уже есть в `self.settings`?

2021-11-05 20:16 UTC, Betchika99 commented on tests/user_side_bar_test.py
> +        settings = UserSettingsPage(driver=self.driver)
здесь лучше перейти на какую-то другую страницу, что проверить непосредственно клик на настройки и увидеть изменение

2021-11-05 20:16 UTC, Betchika99 commented on tests/seller_side_bar_test.py
> +        self.seller_products.side_bar.click_seller_products()
по дефолту мы уже на Всех объявлениях. Чтобы проверить корректность работы, лучше сначала переключиться куда-то в другое место. Или не проверять именно переход, а проверить, что этот пункт меню выделен как активный сразу при открытии страницы

2021-11-05 20:16 UTC, Betchika99 commented on tests/settings_test.py
> +        self.assertEqual(self.settings.pwd_form.get_pwd_change_error(), '', "Нет ошибки")
то есть в случае успеха текста ошибки не будет? тогда текст "Нет ошибки" здесь некорректный. И в чем смысл проверки на отсутствие ошибки? Важно проверить, что то, что мы хотели сделать, было сделано. Отсутствие ошибки - это побочно.

2021-11-05 20:16 UTC, Betchika99 commented on tests/settings_test.py
> +        self.__test__change_password__(old_pwd, new_pwd, conf_pwd)
нужно больше позитивных тестов здесь

2021-11-05 20:16 UTC, Betchika99 commented on tests/create_product_test.py
> +
не хватает позитивных кейсов

2021-11-05 20:16 UTC, Betchika99 commented on tests/create_product_test.py
> +    #     self.assertTrue(promote.is_compare_url(url), "Не открылась страница продвижения")
комментарий нужен?

2021-11-05 20:16 UTC, Betchika99 commented on components/login.py
> +        self.driver.execute_script("document.querySelector(\"{}\").click()".format(self.OUTSIDE))
а почему не работает обычный click? (можем обсудить в тг)

2021-11-05 20:16 UTC, Betchika99 commented on components/review_popup.py
> +        return self.helpers.get_element(self.TITLE).text
здесь не будет краша при взятии `.text`, если элемента нет?

2021-11-05 20:16 UTC, Betchika99 commented on helpers/helpers.py
> +            return self.__find_elements__(selector, By.XPATH, wait)
а если мы что-то третье передали, то что вернется? мб Null хотя бы поставить?

2021-11-05 20:16 UTC, Betchika99 commented on tests/promotion_test.py
> +
этого тесткейса нет в `run_tests.py`. И он падает с ошибками

2021-11-05 20:16 UTC, Betchika99 commented on tests/promotion_test.py
> +        time.sleep(1)
антипаттерн

2021-11-05 20:16 UTC, Betchika99 commented on tests/promotion_test.py
> +        self.assertTrue(self.promote.form.get_purchase_error(), "Выберите какой-нибудь тариф")
текст ошибки здесь не важно проверить?

2021-11-05 20:16 UTC, Betchika99 commented on tests/promotion_test.py
> +        self.assertTrue(self.promote.form.is_advanced_unchecked(), "Нет ошибки")
эти тесты не проверяют функциональность, а нам нужны именно функциональные тесты

2021-11-06 12:07 UTC, alSergey commented on tests/header_test.py
> +        user_id = os.environ.get("USER_ID")
Тут немного другая логика. В ENV у нас лежит тестовый пользователь. Если мы захотим его поменять, то нам придется искать где же мы используем его ID, а так он тоже лежит в ENV. Это как настройка тестов

2021-11-06 12:10 UTC, alSergey commented on tests/registration_test.py
> +        self.assertTrue(self.registration.form.is_error_name(), "Нет ошибки")
Если мы посмотри тест testErrorPasswordInput, то у видим что у нас проверяется 6 кейсов, нам придется просто 6 раз копировать один и тот же код. В данном случае у нас логика заполнения и проверки находится в функции, а в тесте мы только вызываем. Таким образом мы избавляемся от копипасты

2021-11-06 12:13 UTC, alSergey commented on tests/registration_test.py
> +    def testErrorTelephoneInput(self):
У нас +7 вынесено в отдельное поле. Сюда же вводиться только сам телефон, поэтому тут проверка не нужна
<img width="301" alt="image" src="https://user-images.githubusercontent.com/48061668/140609165-2372c927-91c7-4f96-9eef-5a79733af031.png">

2021-11-06 12:17 UTC, alSergey commented on tests/registration_test.py
> +        self.__test_name__(test2)
Нам на лекции рассказывали, что можно объединять похожие тесты, для ускорения тестов. В случае E2E у нас тесты долго проходят и тут нормально, когда ты похожие будешь объединять

2021-11-06 13:59 UTC, alSergey commented on tests/user_await_reviews_test.py
> +        self.assertTrue(self.await_reviews.review_popup.is_error(), "Нет ошибки")
Проблема в том, что после оставления отзыва нам нужно его будет вернуть. Чтобы тесты оставляли после себя то, что было до них. А это сделать очень сложно. Там нужно несколько пользователей, создание товара и тд. Поэтому мы тут отказались от позитивного сценария

2021-11-06 14:19 UTC, alSergey commented on components/login.py
> +        self.driver.execute_script("document.querySelector(\"{}\").click()".format(self.OUTSIDE))
У нас тут используется попап и логика с stopPropogation. Как мне кажется selenium как-то перехватывает события, потому обычный клик не работает. Сделал вот такую логику

2021-11-06 16:26 UTC, alSergey commented on tests/main_test.py
> +        self.assertFalse(self.main.product_card.check_remove_like_product(index), "Не удалось убрать лайк")
Не совсем понятно почему 2 разных теста. После того, как мы поставили лайк мы должны его снять. Какой смысл это разносить по 2 тестам если логика будет дублироваться?

2021-11-06 18:47 UTC, alSergey commented on tests/seller_products_test.py
> +        self.assertFalse(self.seller_products.product_card.check_remove_like_product(index), "Не удалось убрать лайк")
После окончания теста мы должна оставить все так, как было до начала теста. То есть если мы пишем тест на лайк, то нам в конце обязательно нужно снять лайк. Тогда какой смысл это разносить на 2 разных теста?

2021-11-07 13:42 UTC, alSergey commented on tests/search_test.py
> +        self.assertFalse(self.search.search_products.check_remove_like_product(index), "Не удалось убрать лайк")
https://github.com/dkotegov/homework-4/pull/116#discussion_r744156260

2021-11-07 16:55 UTC, IvanGorshkov commented on tests/search_test.py
> +class SearchTest(Test):
мы не сбрасываем потому что селениум запускает каждый раз с чистого листа

2021-11-07 17:03 UTC, IvanGorshkov commented on tests/product_test.py
> +        self.assertTrue(seller_products.is_compare_url(url), "Ошибка редиректа на страницу всех объявлений")
Это метод для каждой страницы, который проверяет ee url.  Ещё мы используем change_path, когда мы хотим поменять url для последующего сравнения с текущим url.

2021-11-07 23:44 UTC, alSergey commented on tests/create_product_test.py
> +
Мы решили отказаться от тестов на создание товара, потому что мы используем Яндекс Апи и берем из него данные, а это работа с внешнем сервисом. Найти вариантов, как уйти от этого не смогли

2021-11-08 00:00 UTC, alSergey commented on tests/promotion_test.py
> +        self.assertTrue(self.promote.form.is_advanced_unchecked(), "Нет ошибки")
У нас по чекистам написаны эти тесты:
* Выделение выбранного тарифа при нажатии на кнопку "Выбрать" и снятие выделение с предыдущего выделенного, если таковой был 
* Галочка при нажатии "не продвигать объявление" и снятие выделение с выбранного перед этим тарифом, если таковой был

2021-11-13 21:40 UTC, Betchika99 approved these changes

2021-12-02 14:29 UTC, dkotegov commented
Принято

2021-12-02 14:29 UTC, closed without merging