WIP: LioKor Team
dkotegov/homework-4 pull request #117
Opened 2021-11-02 23:26 UTC by KoroLion

Authors: @korolion31 and @tyapkin_s

Project: http://mail.liokor.ru

2021-11-04 12:27 UTC, KoroLion commented
reviewed

2021-11-04 14:09 UTC, SergTyapkin commented
reviewed

2021-11-10 09:31 UTC, Betchika99 requested changes
- [ ] очищать ресурсы теста после выполнения (например, удалять пользака, которого зарегистрировали, отправку сообщения и т.п.)
- [ ] убираем лишние комменты
- [ ] убрать слипы
- [ ] убрать лишние рефреши
- [ ] просмотреть функции на предмет стабильности (некоторые тесты мигают)

2021-11-10 09:31 UTC, Betchika99 commented on README.md
> +4. Launch Selenium node with `java -Dwebdriver.chrome.driver="./chromedriver" -Dwebdriver.gecko.driver="./geckodriver" -jar selenium-server-standalone-3.141.59.jar -role node -hub http://localhost:44
сначала лучше запустить хаб, а потом ноду

2021-11-10 09:31 UTC, Betchika99 commented on README.md
> +5. Launch Selenium hub with `java -jar selenium-server-standalone-3.141.59.jar -role hub`
стоит уточнить, что это надо делать в папке `bin`

2021-11-10 09:31 UTC, Betchika99 commented on README.md
> +6. Navigate to project root and start testing with `python3 run_tests.py`
первый запуск не сработает в таком случае, т.к. не установлены пакеты. Нужно добавить на всякий инструкцию для первого запуска. Посмотрите в сторону виртуального окружения и requirements.txt

2021-11-10 09:31 UTC, Betchika99 commented on pages/base_page.py
> +            self.locate_el(self.base_css_sel)
может быть здесь сначала проверить, что в `self.base_css_sel` есть что-то? потому что по дефолту у вас там пустая строка и зачем тогда лишний раз функцию вызывать

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/auth_test.py
> +        auth_email = self.page.auth()
внутри `auth` вы еще раз вызываете метод `open`. точно нужен этот повтор?

2021-11-10 09:31 UTC, Betchika99 commented on pages/auth_page.py
> +            self.click_login_btn()
это выглядит как костыль. Ваши тесты должны проверять валидное поведение сервиса. Если на сервисе есть проблема, что бек возвращает 500, это надо чинить, а не костылить тесты. 
в больших проектах, когда баги не успевают чинить, а тесты очень часто мигают, их либо ретраят (при падении перезапускают до N раз, чтобы тест точно выполнился), либо скипают и ставят задачу

2021-11-10 09:31 UTC, Betchika99 commented on pages/auth_page.py
> +        return main_page.get_authenticated_user_email()
кажется, лучше это обернуть в отдельный метод получения текущего email-а, который дернуть из тестов. Иначе логика немного смешивается и из теста непонятно, что должен вернуться email именно здесь

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/auth_test.py
> +        actual_username = auth_email.split('@')[0].lower()
логин - это всегда часть почты до собачки? вы это где-то гарантируете у себя в сервисе?

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/auth_test.py
> +        self.assertNotEqual(len(err), 0)
почему не проверять содержимое ошибки? может там что-то вообще не корректное отображается. Здесь и далее

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/auth_test.py
> +        self.assertNotEqual(len(password_error), 0)
можно еще проверить, когда невалидный username, но валидный пароль

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/auth_test.py
> +        self.assertEqual(SignupPage(self.driver).is_opened(), True)
можно вместо `assertEqual` сразу использовать `assertTrue`

2021-11-10 09:31 UTC, Betchika99 commented on pages/base_page.py
> +        pyautogui.press('enter')
а почему вместо этого просто не передать в инпут файла адрес вашего локального файлика через `send_keys`?

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/profile_test.py
> +        self.assertTrue('success' in self.page.get_popup().get_attribute('class'))
почему здесь проверяете наличие класса? кажется, что нужно проверять урл картинки, что мы загрузили именно то, что нужно

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/profile_test.py
> +        self.driver.refresh()
перезагрузка - выглядит, как костыль. У вас в риалтайме данные не меняются?

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/profile_test.py
> +        self.assertEqual(self.auth_page.is_opened(), True)
кажется, это лишнее. И так же произошел редирект на авторизацию

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/profile_test.py
> +    def test_good_avatar(self):
не проходит с моими версиями библиотек
<img width="857" alt="image" src="https://user-images.githubusercontent.com/34346716/141000941-9f181fb0-84b0-446f-9bdf-a43bc4cec386.png">

возможно починится, если вы сделаете requirements.txt

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/signup_test.py
> +    def generate_random_username(self):
т.к. это не тест, а просто приватный метод, давайте пометим его как приватный (в начале названия добавьте __)

2021-11-10 09:31 UTC, Betchika99 commented on tests/profile/signup_test.py
> +        self.page.set_email(self.GOOD_EMAIL)
не вижу удаление этого пользователя после создания. у вас может быть несколько пользаков с одним email-ом? кажется, это не корректно

2021-11-10 09:31 UTC, Betchika99 commented on pages/main_page.py
> +        # return self.locate_el(self.MESSAGE_LAST_ANY).get_attribute('class').find('right-block') != -1
нужен коммент?

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/main_base_test.py
> +        self.assertTrue(self.page.isLastMessageYours(), "Last message not yours")
а почему проверяете, что просто последнее сообщение мое? а если я уже отправляла сообщения и последнее мое, а вот текущее отправление не появилось в списке? некорректная проверка

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/messages_test.py
> +        self.assertEqual(self.page.getLastYourMessageTitle(), "Title STRONG TITLE")
а с чем сравниваем?

2021-11-10 09:31 UTC, Betchika99 commented on pages/main_page.py
> +                time.sleep(0.05)
антипаттерн

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/messages_test.py
> +        self.driver.refresh()
а почему рефреш? можно же сразу увидеть и сравнить текст сообщения

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/editor_test.py
> +        cls.page.driver.maximize_window()
а здесь разве не open страницы должен быть?

2021-11-10 09:31 UTC, Betchika99 commented on pages/main_page.py
> +        el.send_keys(Keys.CONTROL + 'a')
добавьте плиз вместо CONTROL еще COMMAND, чтобы на маке тесты не падали, здесь и далее

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/editor_test.py
> +    def test_editor_photo_positive(self):
не проходит с моими версиями библиотек
<img width="898" alt="image" src="https://user-images.githubusercontent.com/34346716/141011283-4ab1b130-0bcc-4e15-a463-3f155f125759.png">

возможно починится, если вы сделаете requirements.txt

2021-11-10 09:31 UTC, Betchika99 commented on pages/main_page.py
> +            except selenium.common.exceptions.StaleElementReferenceException:
лучше читаться будет, если наверно в импортах этот эксепшен добавить, а отсюда убрать эту длинную строку. И оставить только StaleElementReferenceException

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/dialogues_test.py
> +        self.assertTrue(self.page.isDialogueNotOpened(), "Deleted dialogue already opened")
кажется, здесь лучше проверять количество диалогов

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/dialogues_test.py
> +        self.driver.refresh()
зачем обновлять страницу?

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/dialogues_test.py
> +    def test_open_many_dialogues(self):
кажется, здесь не открываются много диалогов, а просто есть много диалогов. Лучше более конкретное название

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/folders_test.py
> +class FoldersTest(MainBaseTest):
не хватает tearDown

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/folders_test.py
> +        self.assertTrue(self.page.isFoldersExpanded(), "Folders not expanded")
избыточный тест, т.е. это проверяется внутри остальных тестов ниже

2021-11-10 09:31 UTC, Betchika99 commented on tests/main/main_base_test.py
> +            return
мб это убрать и переделать проверку на ` if renameTo is not None:`? чтобы избежать дублей кода

2021-11-10 09:31 UTC, Betchika99 commented on pages/main_page.py
> +        el.send_keys(Keys.ENTER)
лучше здесь перед вводом нового значения именно очистить инпут, а не заменить имя выделением. Так будет стабильнее

2021-11-10 16:33 UTC, KoroLion commented on tests/main/editor_test.py
> +    def test_editor_photo_positive(self):
это Windows?

2021-11-10 16:36 UTC, KoroLion commented on pages/main_page.py
> +                time.sleep(0.05)
но ведь тут не просто слип, а ожидание события

2021-11-10 16:37 UTC, KoroLion commented on tests/profile/signup_test.py
> +        self.page.set_email(self.GOOD_EMAIL)
функции удаления пользователя нет в проекте, несколько пользователей с одним запасным email могут быть

2021-11-10 16:40 UTC, KoroLion commented on tests/profile/profile_test.py
> +        self.assertTrue('success' in self.page.get_popup().get_attribute('class'))
урл картинки поменяется на рандомный, напр. https://mail.liokor.ru/api/media/avatars/930c7a86e4562e925108d2bb6d9bb97a49ec49a2b92b8169044a54668ccf1d8e.jpg

2021-11-10 16:40 UTC, KoroLion commented on tests/profile/profile_test.py
> +        self.driver.refresh()
в риалтайме у нас только то, что делает пользователь. Всё остальное (получение сообщения, ...) - нет.

2021-11-10 16:41 UTC, KoroLion commented on tests/profile/profile_test.py
> +        self.assertTrue('success' in self.page.get_popup().get_attribute('class'))
урл картинки поменяется на рандомный, напр. https://mail.liokor.ru/api/media/avatars/930c7a86e4562e925108d2bb6d9bb97a49ec49a2b92b8169044a54668ccf1d8e.jpg

2021-11-10 16:43 UTC, KoroLion commented on tests/profile/auth_test.py
> +        actual_username = auth_email.split('@')[0].lower()
да, у нас ведь почтовый сервис - все пользователи это логин + @liokor.ru

2021-11-10 16:44 UTC, KoroLion commented on pages/auth_page.py
> +            self.click_login_btn()
боюсь, мы не успеем это починить на беке

2021-11-10 18:01 UTC, KoroLion commented on README.md
> +4. Launch Selenium node with `java -Dwebdriver.chrome.driver="./chromedriver" -Dwebdriver.gecko.driver="./geckodriver" -jar selenium-server-standalone-3.141.59.jar -role node -hub http://localhost:44
ок

2021-11-10 18:01 UTC, KoroLion commented on README.md
> +5. Launch Selenium hub with `java -jar selenium-server-standalone-3.141.59.jar -role hub`
ок

2021-11-10 18:03 UTC, KoroLion commented on README.md
> +6. Navigate to project root and start testing with `python3 run_tests.py`
добавил пункт про установку Python зависимостей

2021-11-11 14:45 UTC, KoroLion commented on tests/profile/auth_test.py
> +        self.assertEqual(SignupPage(self.driver).is_opened(), True)
ок

2021-11-11 14:45 UTC, KoroLion commented on pages/base_page.py
> +        pyautogui.press('enter')
да, так гораздо лучше работает

2021-11-11 14:47 UTC, KoroLion commented on tests/profile/profile_test.py
> +        self.assertEqual(self.auth_page.is_opened(), True)
нет, это не лишнее. Это проверка, что пользователь действительно вышел. Т.к. при попытке зайти в профиль, его кидает обратно на авторизацию.

2021-11-11 14:49 UTC, KoroLion commented on tests/profile/auth_test.py
> +        self.assertNotEqual(len(err), 0)
но ведь этот тест проверяет, что при неправильном логине в поле с логином появилась ошибка. Разве, этого не достаточно?

2021-11-11 14:50 UTC, KoroLion commented on tests/profile/profile_test.py
> +    def test_good_avatar(self):
файл requirements.txt есть. Просто на маке не работает ф-я pyautogui.getActiveWindow()

2021-11-11 14:51 UTC, KoroLion commented on tests/main/editor_test.py
> +    def test_editor_photo_positive(self):
как уже писал выше, на маке нет ф-и pyautogui.getActiveWindow()

2021-11-11 14:53 UTC, KoroLion commented on tests/profile/signup_test.py
> +    def generate_random_username(self):
ок

2021-11-11 14:54 UTC, KoroLion commented on pages/main_page.py
> +        # return self.locate_el(self.MESSAGE_LAST_ANY).get_attribute('class').find('right-block') != -1
убрал

2021-11-11 14:55 UTC, KoroLion commented on pages/base_page.py
> +            self.locate_el(self.base_css_sel)
ок

2021-11-12 15:45 UTC, KoroLion commented on tests/profile/auth_test.py
> +        self.assertNotEqual(len(password_error), 0)
ok

2021-11-12 15:52 UTC, KoroLion commented on tests/profile/auth_test.py
> +        auth_email = self.page.auth()
нужен, т.к. этот метод вызывается в тестах, которые работают на других страницах

2021-11-12 15:59 UTC, KoroLion commented on pages/auth_page.py
> +        return main_page.get_authenticated_user_email()
ок

2021-11-12 16:08 UTC, KoroLion commented on tests/profile/profile_test.py
> +        self.assertTrue('success' in self.page.get_popup().get_attribute('class'))
добавил проверку, что url картинки поменялся

2021-11-12 16:09 UTC, KoroLion commented on tests/profile/profile_test.py
> +        self.driver.refresh()
здесь это рефреш, чтобы убедиться, что серв реально поменял данные

2021-11-12 17:02 UTC, KoroLion commented on pages/main_page.py
> +                time.sleep(0.05)
переписал

2021-11-12 17:11 UTC, KoroLion commented on pages/main_page.py
> +            except selenium.common.exceptions.StaleElementReferenceException:
ок

2021-11-12 17:34 UTC, KoroLion commented on pages/main_page.py
> +        el.send_keys(Keys.CONTROL + 'a')
ок

2021-11-12 17:35 UTC, KoroLion commented on tests/main/folders_test.py
> +        self.assertTrue(self.page.isFoldersExpanded(), "Folders not expanded")
убрал

2021-11-12 18:05 UTC, KoroLion commented on tests/main/main_base_test.py
> +        self.assertTrue(self.page.isLastMessageYours(), "Last message not yours")
переписал тест и убрал эту проверку из этого места

2021-11-12 18:06 UTC, KoroLion commented on tests/main/messages_test.py
> +        self.driver.refresh()
смысл теста, что сообщение сохраняется в редакторе, если пользователь перезашёл на страницу

2021-11-12 18:07 UTC, KoroLion commented on tests/main/messages_test.py
> +        self.assertEqual(self.page.getLastYourMessageTitle(), "Title STRONG TITLE")
мы убеждаемся, что новый тайтл - это старый, из которого вырезан HTML

2021-11-12 18:17 UTC, KoroLion commented on tests/main/dialogues_test.py
> +        self.assertTrue(self.page.isDialogueNotOpened(), "Deleted dialogue already opened")
этот тест вообще не нужен, т.к. диалоги удаляются в tearDown - убрал его

2021-11-12 18:25 UTC, KoroLion commented on tests/main/dialogues_test.py
> +        self.driver.refresh()
если не обновить страницу, то поиск работать не будет

2021-11-12 18:28 UTC, KoroLion commented on tests/main/dialogues_test.py
> +    def test_open_many_dialogues(self):
переименовал

2021-11-12 18:37 UTC, KoroLion commented on pages/main_page.py
> +        el.send_keys(Keys.ENTER)
исправил

2021-11-12 18:40 UTC, KoroLion commented on tests/main/main_base_test.py
> +            return
поправил

2021-11-12 19:22 UTC, KoroLion commented on tests/main/folders_test.py
> +class FoldersTest(MainBaseTest):
добавил

2021-11-12 20:51 UTC, KoroLion commented on tests/main/editor_test.py
> +        cls.page.driver.maximize_window()
да, исправил

2021-11-12 20:51 UTC, KoroLion commented on tests/main/editor_test.py
> +    def test_editor_photo_positive(self):
сделал так, что этот тест скипается, если ось - не винда

2021-11-12 20:51 UTC, KoroLion commented on tests/profile/profile_test.py
> +    def test_good_avatar(self):
сделал так, что этот тест скипается, если ось - не винда

2021-12-02 14:34 UTC, dkotegov commented
Принято

2021-12-02 14:34 UTC, closed without merging