RedTech
dkotegov/homework-4 pull request #119
Opened 2021-11-04 20:48 UTC by VolkovNik

Волков Никита
Будкин Григорий
Чеклин Павел
Чеклист: http://jira.bmstu.cloud/browse/QA-1349

2021-11-04 20:49 UTC, VolkovNik commented
аппрув

2021-11-04 20:49 UTC, paulnopaul commented
аппрув

2021-11-04 20:51 UTC, GregoryBS commented
Approved

2021-11-30 17:32 UTC, Betchika99 requested changes
- [ ] Использовать везде одинаковые методы (для wait-проверок где-то используются свои утилиты, а где-то пишется новый wait, лучше везде использовать свои утилиты)
- [ ] Вынести переменные окружения bash а переменные окружения проекта (файл .env)
- [ ] описать в ридми как запускать ваши тесты
- [ ] Объединить тесты в тесткейсы (чтобы в файле запуска тестов они были не разбросанные по разным файлам, а собраны, например, для одной страницы в один файл (как у вас сделано в соответствующих чеклистах)

2021-11-30 17:32 UTC, Betchika99 commented on pages/login.py
> +        form.set_password(os.environ['PASSWORD'])
лучше получать через `.get`

2021-11-30 17:32 UTC, Betchika99 commented on run_tests.py
> +        unittest.makeSuite(FindActorTest)
лучше сгруппировать тесты по тестовым кейсам, как у вас было в чеклистах. Смысл в том, чтобы разбивать проект на страницы, где на одну страницу один тесткейс, внутри много тестов

2021-11-30 17:32 UTC, Betchika99 commented on pages/series.py
> +        ).text
а почему здесь не используется ваша утилита `wait_for_element_by_selector`?

2021-11-30 17:32 UTC, Betchika99 commented on pages/login.py
> +        main_page = MainPage(self.driver)
А зачем здесь создание страницы, если оно не проверяется?

2021-11-30 17:32 UTC, Betchika99 commented on pages/login.py
> +        return True
То есть метод вернёт либо тру, либо ничего (упадёт эксепшен)? По коду немного странно выглядит

2021-11-30 17:32 UTC, Betchika99 commented on run_tests.py
> +        # unittest.makeSuite(WrongPasswordLoginTest), # bug
Лучше не комментить тесты, а скипать с пометкой, что «будет сделано в задаче N»

2021-11-30 17:32 UTC, Betchika99 commented on run_tests.py
> +        # unittest.makeSuite(SignUpTest), # work once
Не понятный коммент, в чем вопрос?

2021-11-30 17:32 UTC, Betchika99 commented on tests/details/tests_with_auth/details_buttons_tests.py
> +            command_executor='http://127.0.0.1:4444/wd/hub',
Здесь обязательно заново хаб подключать? Почему не сделать как в остальных тестах?

2021-11-30 17:32 UTC, Betchika99 commented on tests/login/invalid_email_login_test.py
> +        auth_page.auth_with('invalidemailcom', 'random_password')
Лучше вынести эти значения в константы. Здесь и далее

2021-12-01 17:46 UTC, paulnopaul commented on pages/series.py
> +        ).text
fixed

2021-12-02 12:44 UTC, paulnopaul commented on pages/login.py
> +        form.set_password(os.environ['PASSWORD'])
+

2021-12-02 14:42 UTC, dkotegov commented
Принято

2021-12-02 14:42 UTC, closed without merging