BERM ДЗ номер 4
dkotegov/homework-4 pull request #120
Opened 2021-11-04 20:58 UTC by astlok

findfreelancer.ru

2021-11-13 19:10 UTC, artemMur requested changes
Нужно исправить:
1) Декомпозиция (убрать steps, убрать лишние pages)
2) Оформление проекта (почистить репозиторий, отформатировать код).
3) Отредактировать описание к некоторым кейсам
4) Перенести assert и инициализацию fixtures в тест

2021-11-13 19:10 UTC, ghost commented on .idea/.gitignore
> +# Default ignored files
необходимо удалить эту папку из репозитория, как и другие бинарные файлы

2021-11-13 19:10 UTC, ghost commented on tests/AllOrdersStep.py
> +    def test_clickable_fields_in_result_card(self):
очень важно, чтобы проверка (assert) и инициализация тестовых данных (fixtures) выполнялась в самом тесте. Сейчас из тест кейса нельзя понять, что он проверяет, так как все скрыто в steps. На мой взгляд это неправильно.

Паттерн pages позволяет вынести из тест кейса часть логики и сделать тесты болеее читаемыми за счет меньшего колличества повторений setup кода, но не стоит выносить саму проверку и тестовые данные из тест кейса, это делает его безполезным и усложняет чтение кода

2021-11-13 19:10 UTC, ghost commented on steps/AllOrdersStep.py
> +class AllOrdersStep(DefaultStep):
не совсем понимаю, зачем слой steps. На мой взгляд с учетом pages это излишняя абстракция.

Я рекомандую избравиться от steps и всю логику выполнять в pages.

Сейчас часть методов в pages, часть в steps, что является бесполезным усложением.

Мне кажется, что можно сделать pages в котором будет setup страницы и все необходимые методы, которые требуются для проверок. То есть steps это просто методы pages, а не отдельный класс. И в самом юнит тесте работать только с объектом pages. Это уменьшит колличество кода и уберет ненужную абстракцию. Код должен быть простым и понятным. Всегда стоит помнить про KISS и DRY

2021-11-13 19:10 UTC, ghost commented on tests/default.py
> +    PASSWORD_EXECUTOR = '123456Qq'  # os.environ['PASSWORD']
пароли никогда не стоит хранить в репозитории. Это может войти в привычку

2021-11-13 19:10 UTC, ghost commented on pages/VacancyPage.py
> +        self.waitOfVisible(self.SELECT_BUTTON)
здесь лучше использовать метод check_select_button, а не повторять код оттуда, так как если логика работы с этим компонентом измениться, то ее придется менять в двух местах

2021-11-13 19:10 UTC, ghost commented on tests/VacancyTest.py
> +        is_open = step.check_change_vacancy()
почему переменная называется is_open и проверяется значение, что оно True, но в описании теста написано, что оно не должно открываться?

2021-11-13 19:10 UTC, ghost commented on tests/AuthTest.py
> +        authStep.check_err_auth()
нужен явный assert в тесте

2021-11-13 19:10 UTC, ghost commented on tests/AuthTest.py
> +                         f'не совпадает с ожидаемым ${self.LOGIN_EXECUTOR}'
Мне кажется, стоит поменять формулировку, так как из нее не понятна суть ошибки. Из этой формулировки кажется, что авторизация не прошла из-за неправильного логина, хотя это не всегда так

2021-11-13 19:10 UTC, ghost commented on tests/AuthTest.py
> +        """
это очень хорошая практика писать docstrings, возможно, стоит добавить описание для test suite, чтобы добавить доп. контекст к тестам

2021-11-13 19:10 UTC, ghost commented on tests/ChangeOrderTest.py
> +        order, expect_order = step.check_change_order()
мне кажется, что инициализация fixture должна быть в самом тесте, а не в pages

2021-11-13 19:10 UTC, ghost commented on tests/ChangeOrderTest.py
> +        self.assertEqual(   order,
возможно, стоит воспользоваться автоформатированием на проекте. Мой любимый форматер это [black](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#:~:text=Black%20prefers%20double%20quotes%20(%20%22%20and,more%20backslash%20escapes%20than%20before. )

2021-11-13 19:10 UTC, ghost commented on tests/ChangeOrderTest.py
> +                            f'Ошибка инпута не появилась'
почему-то is_err = True, но в описании написано, что ошибка не появилась

2021-11-13 19:10 UTC, ghost commented on tests/ClientRegTest.py
> +        step.check_err_login()
делать assert в test case

2021-11-13 19:10 UTC, ghost commented on tests/MainTest.py
> +class MainTest(DefaultTest):
на мой взгляд это плохое название из которого нельзя понять, что именно проверяется

2021-11-13 19:10 UTC, artemMur commented on tests/OrderTest.py
> +class OrderTest(DefaultTest):
Если посмотреть pages ChangeOrder и OrderPage, то setup у них одинаковый, это плохо, потому что серьезно ухудшает возможность модификации кода.

Допустим, вы хотите проверить одну страницу но с разнимы тестовыми сценариями. В таком случае стоит разнести проверки по разным test suite, но использовать один pages, а не создавать несколько pages на каждый test suite, который проверяет одну страницу.

2021-11-15 19:46 UTC, astlok commented on tests/VacancyTest.py
> +        is_open = step.check_change_vacancy()
Наоборот, в описании написано что оно должно открыться и тест валиться если оно не открылось

2021-11-15 19:49 UTC, astlok commented on tests/ChangeOrderTest.py
> +                            f'Ошибка инпута не появилась'
Тоже самое, что и в предыдущем случае, is_err = True, ошибка должна появится, но если не появляется тест валится

2021-11-15 19:54 UTC, astlok commented on tests/VacancyTest.py
> +        is_open = step.check_change_vacancy()
Наоборот, в описании написано что оно должно открыться и тест валиться если оно не открылось

2021-11-15 20:00 UTC, astlok commented on tests/OrderTest.py
> +class OrderTest(DefaultTest):
Не очень понял, что подразумевается, под одинаковым setup, страницы существенно разные и их достаточно сложно и главное не понятно для чего разделять, ведь все что у них одинаковое это начальная страница, остальная логика тестов полностью отличается

2021-11-15 20:08 UTC, AzisHop commented on tests/MainTest.py
> +class MainTest(DefaultTest):
Поправлено

2021-11-15 20:45 UTC, artemMur commented on tests/OrderTest.py
> +class OrderTest(DefaultTest):
спасибо за ответ. Из моего комментария, действительно, сложно понять суть проблемы.

 Я имел в виду, что ChangeOrder и OrderPage это два набора тестов, которые должны ссылаться на общий класс pages с всеми необходимыми методами для этих тестов, а не на две реализации pages одной страницы.

2021-12-02 14:42 UTC, dkotegov commented
Принято

2021-12-02 14:42 UTC, closed without merging