ДЗ4
dkotegov/homework-4 pull request #17
Opened 2017-06-04 20:38 UTC by IlyaNikk

Добрый вечер. Я, Илья Никитин, выполнил дз, мой чек-лист http://st-jira.tech-mail.ru/browse/TECH-676

2017-06-06 16:58 UTC, dkotegov requested changes

2017-06-06 16:58 UTC, dkotegov commented on tests/elements/auth.py
> +        raise Exception('Timeout waiting for element is enabled')
Велосипед, для этого есть WebDriverWait и ExpectedCondition.element_to_be_clickable()

2017-06-06 16:58 UTC, dkotegov commented on tests/elements/base.py
> +        except Exception as e:
Плохо перехватывать всё

2017-06-06 16:58 UTC, dkotegov commented on tests/elements/create_topic.py
> +    locator = (By.XPATH, "//input[@id='id_title']")
А зачем отдельный класс на каждый элемент?
Давайте сгруппируем по страницам

2017-06-06 16:58 UTC, dkotegov commented on tests/pages/auth.py
> +from tests.elements.auth import *
Плохо импортировать *
Получите головную боль при дебаге

2017-06-06 16:58 UTC, dkotegov commented on tests/pages/auth.py
> +        self.wait()
Это зашито в driver.get() из коробки
Он дождется полной загрузки страницы

2017-06-06 16:58 UTC, dkotegov commented on tests/pages/base.py
> +        raise Exception('Timeout waiting for page loaded')
И тут

2017-06-06 16:58 UTC, dkotegov commented on tests/topics.py
> +        except Exception as e:
И тут

2017-06-07 15:13 UTC, IlyaNikk commented
Поправил

2017-06-13 03:01 UTC, dkotegov commented on tests/elements/auth.py
> +    #     raise Exception('Timeout waiting for element is enabled')
Не выглядит законченным ;)

2017-06-13 03:02 UTC, dkotegov commented
Принято

2017-06-13 03:02 UTC, closed without merging