Зерминова Евфросиния
dkotegov/homework-4 pull request #19
Opened 2017-06-09 16:31 UTC by Evfrosiniya

Не знаю как в test_send_empty_message избавиться от time.sleep(1)

2017-06-09 16:32 UTC, Evfrosiniya commented
Чек-лист
http://st-jira.tech-mail.ru/browse/TECH-686

2017-06-13 02:56 UTC, dkotegov requested changes

2017-06-13 02:56 UTC, dkotegov commented on extentions.py
> +    return time
Велосипед ;)

2017-06-13 02:56 UTC, dkotegov commented on tests.py
> +from elements import *
Старайтесь не импортировать *
Будут сложности при дебаге

2017-06-13 02:56 UTC, dkotegov commented on tests.py
> +        self.driver.refresh()
А зачем рефреш?

2017-06-13 02:56 UTC, dkotegov commented on tests.py
> +        time.sleep(1)
Ждите отрисовки формы

2017-06-13 02:56 UTC, dkotegov commented on tests.py
> +        self.assertFalse(messagebox_text == '')
assertNotEqual

2017-06-13 02:56 UTC, dkotegov commented on tests.py
> +        self.driver.refresh()
Костыль, чтобы не использовать sleep? ;)

2017-06-13 14:30 UTC, Evfrosiniya commented
Исправила замечания

2017-06-13 14:32 UTC, Evfrosiniya commented on tests.py
> +        self.driver.refresh()
ага)

2017-06-14 15:05 UTC, dkotegov commented
Принято

2017-06-14 15:05 UTC, closed without merging