Сделал домашку
dkotegov/homework-4 pull request #24
Opened 2017-07-01 12:05 UTC by romvano

Дима, привет! Посмотри, пожалуйста, мое ДЗ!

(Иван Романов)

2017-07-01 14:23 UTC, dkotegov requested changes

2017-07-01 14:23 UTC, dkotegov commented on tests/auth.py
> +    print 'authenticated!'
Дебажные принты надо убрать :)

2017-07-01 14:23 UTC, dkotegov commented on tests/create_page/create_page_tests.py
> +class Test1(CreatePageTest):
Плохое название, не понятно что проверяется

2017-07-01 14:23 UTC, dkotegov commented on tests/create_page/create_page_tests.py
> +    '''Check if poll options appear'''
В одном классе (сьюте) может быть несколько тестов :)

2017-07-01 14:23 UTC, dkotegov commented on tests/create_page/create_page_tests.py
> +    def test(self):
И тут

2017-07-01 14:23 UTC, dkotegov commented on tests/create_page/create_page_tests.py
> +        self.assertEqual(description, self.BLOG_DESCRIPTION, 'Blog description on create page is incorrect')
А зачем это проверять?

2017-07-01 14:23 UTC, dkotegov commented on tests/create_page/create_page_tests.py
> +        self.assertTrue(new_number - old_number == 1, 'Poll additional answer doesn\'t appear')
assertNotEqual

2017-07-01 14:23 UTC, dkotegov commented on tests/event_list_page/event_list_page.py
> +        return 'https://park.mail.ru/blog/33/topic/create/'
А зачем захардкодил блог 33?

2017-07-01 14:23 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +        wait_for_element_load(self.driver, (By.XPATH, EventListPage.UNIQUE))
Что проверяет этот тест?

2017-07-01 14:23 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertTrue(is_url_correct, 'Header doesn\'t redirect to event page')
Вместо урла лучше проверять контент на странице

2017-07-01 14:23 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +        is_url_correct = re.match(r'^http://ftest\.tech-mail\.ru/blog/topic/view/[0-9]+/$',
А зачем регулярка? Можно проще :)

2017-07-01 14:23 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +            pass
А зачем перехватывать и пропускать? Тест после этого должен пройти или упасть?

2017-07-01 14:23 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(old_text, new_text, 'Registration button text changed')
Так он должен поменяться или нет? ;)

2017-07-01 14:23 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(old_color, new_color, 'Registration button color changed')
И тут

2017-07-01 14:23 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(self.driver.current_url, EventListPage.get_url(), 'Subheader link is incorrect')
Экономия на спичках. Тестовые данные должны быть в тесте

2017-07-01 14:23 UTC, dkotegov commented on tests/event_page/event_page.py
> +            return True
return True можно перенести внутрь try

2017-07-01 14:23 UTC, dkotegov commented on tests/event_page/event_page_tests.py
> +        wait_for_element_load(self.driver, (By.XPATH, EventPage.UNIQUE))
Подозреваю, что это нужно перенести в setUp

2017-07-01 14:23 UTC, dkotegov commented on tests/event_page/event_page_tests.py
> +            topic_footer.vote_down()
Костыль. Перед тестом система должна быть приведена в исходное состояние.

2017-07-01 14:23 UTC, dkotegov commented on tests/event_page/event_page_tests.py
> +        self.assertTrue(comments_block.is_textarea_visible(), 'Textarea is not visible - adding a comment')
Лучше проверять текст комментария

2017-07-01 14:23 UTC, dkotegov commented on tests/event_page/event_page_tests.py
> +        self.assertTrue(self.event_page.is_alert_shown(), 'Alert not shown - adding a comment twice')
А тут содержимое алерта, хотя лучше то, как страница меняется после него

2017-07-01 14:23 UTC, dkotegov commented on tests/utils.py
> +        pass
?

2017-07-01 21:58 UTC, romvano commented on tests/create_page/create_page_tests.py
> +        self.assertEqual(description, self.BLOG_DESCRIPTION, 'Blog description on create page is incorrect')
Потому что там даже баг в этом месте: по умолчанию выбран блог "Мероприятия", а описание к нему выводится только если его выбрать в выпадающем списке повторно. Реально в тесте надо проверять, соответствует ли описание блога описанию блога мероприятий.

2017-07-01 23:14 UTC, romvano commented on tests/create_page/create_page_tests.py
> +        self.assertTrue(new_number - old_number == 1, 'Poll additional answer doesn\'t appear')
Я хотел проверить точное значение, так что сделаю assertEqual(difference, 1)

2017-07-01 23:15 UTC, romvano commented on tests/event_list_page/event_list_page.py
> +        return 'https://park.mail.ru/blog/33/topic/create/'
Раздел, который я проверяю, - это Мероприятия, они на сайте - блог №33

2017-07-01 23:17 UTC, romvano commented on tests/event_list_page/event_list_page_tests.py
> +        wait_for_element_load(self.driver, (By.XPATH, EventListPage.UNIQUE))
Ну это было то, что надо писать в setUp

2017-07-01 23:25 UTC, romvano commented on tests/event_list_page/event_list_page_tests.py
> +        is_url_correct = re.match(r'^http://ftest\.tech-mail\.ru/blog/topic/view/[0-9]+/$',
Ну тут нужно сразу проверить и начало строки, и конец, и то, что в середине должны быть цифры

2017-07-02 00:23 UTC, romvano commented on tests/event_page/event_page_tests.py
> +        self.assertTrue(comments_block.is_textarea_visible(), 'Textarea is not visible - adding a comment')
Этот тест не на публикацию комментария, а на появление поля ввода для него

2017-07-02 14:17 UTC, romvano commented on tests/auth.py
> +    print 'authenticated!'
Убрал

2017-07-02 14:17 UTC, romvano commented on tests/create_page/create_page_tests.py
> +class Test1(CreatePageTest):
исправил

2017-07-02 14:17 UTC, romvano commented on tests/create_page/create_page_tests.py
> +    def test(self):
исправил

2017-07-02 14:18 UTC, romvano commented on tests/create_page/create_page_tests.py
> +    '''Check if poll options appear'''
сделал

2017-07-02 14:18 UTC, romvano commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertTrue(is_url_correct, 'Header doesn\'t redirect to event page')
переделал

2017-07-02 14:18 UTC, romvano commented on tests/event_list_page/event_list_page_tests.py
> +            pass
переделал через JS

2017-07-02 14:18 UTC, romvano commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(old_text, new_text, 'Registration button text changed')
и это)

2017-07-02 14:19 UTC, romvano commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(old_text, new_text, 'Registration button text changed')
не должен, ибо регистрация уже закончена

2017-07-02 14:19 UTC, romvano commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(old_color, new_color, 'Registration button color changed')
и тут не должен. На портале для простых смертных студентов нет возможности добавить в топик такую кнопку

2017-07-02 14:20 UTC, romvano commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(self.driver.current_url, EventListPage.get_url(), 'Subheader link is incorrect')
учел

2017-07-02 14:20 UTC, romvano commented on tests/event_page/event_page.py
> +            return True
перенес

2017-07-02 14:20 UTC, romvano commented on tests/event_page/event_page_tests.py
> +        wait_for_element_load(self.driver, (By.XPATH, EventPage.UNIQUE))
перенес

2017-07-02 14:21 UTC, romvano commented on tests/event_page/event_page_tests.py
> +            topic_footer.vote_down()
Сделал, используя второго пользователя. Поскольку создать нового студента или препода не получится, нужно взять еще чей-то аккаунт и проверить с помощью него. Для этого я ввел переменные окружения LOGIN2 и PASSWORD2

2017-07-02 14:22 UTC, romvano commented on tests/event_page/event_page_tests.py
> +        self.assertTrue(self.event_page.is_alert_shown(), 'Alert not shown - adding a comment twice')
проверил содержимое алерта

2017-07-02 14:22 UTC, romvano commented on tests/utils.py
> +        pass
это была заглушка)

2017-07-02 14:24 UTC, romvano commented
Дим, я переделал! Посмотри, пожалуйста!

2017-07-02 19:13 UTC, dkotegov requested changes

2017-07-02 19:13 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +                                     'Header doesn\'t redirect to event page')
Из этого блока лучше оставить только
```python
wait_for_element_load(self.driver, (By.XPATH, EventPage.UNIQUE))
self.assertRegexpMatches(self.driver.current_url,
                                     r'^http://ftest\.tech-mail\.ru/blog/topic/view/[0-9]+/',
                                     'Header doesn\'t redirect to event page')
```
Потому что если не пройдет wait, тест и так упадет
А вторая проверка бессмыслена если упала первая
Проверку урла лучше переделать на проверку контента на странице

2017-07-02 19:13 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +                                       'document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.click()')
Выглядит как костыль

2017-07-02 19:13 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(old_text, new_text, 'Registration button text changed')
А в каком случае она может поменяться?
Похоже на проверку того, что "бага нет", а не того, что кнопка работает.

2017-07-02 19:13 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +        self.assertEqual(old_color, new_color, 'Registration button color changed')
Аналогично

2017-07-02 19:13 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +            self.fail('Subheader link is incorrect')
Тест без проверок? Кажется я рассказывал про такой антипаттерн ;)

2017-07-02 19:13 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +                                 'Read further link doesn\'t scroll')
И тут

2017-07-02 19:13 UTC, dkotegov commented on tests/event_list_page/event_list_page_tests.py
> +            self.fail('Create topic link is incorrect')
И тут

2017-07-02 19:13 UTC, dkotegov commented on tests/event_page/event_page.py
> +            return True
`return True` можно перенести в `try`

2017-07-02 19:13 UTC, dkotegov commented on tests/event_page/event_page.py
> +        return self.driver.find_element_by_xpath(self.CONTAINER_PATH).text != ''
Поиск выполнится 2 раза

2017-07-02 19:13 UTC, dkotegov commented on tests/event_page/event_page.py
> +        return self.driver.find_element_by_xpath(self.TEXTAREA_PATH).is_displayed()
И тут

2017-07-02 19:13 UTC, dkotegov commented on tests/event_page/event_page_tests.py
> +                                       'document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.click()')
И тут

2017-07-21 20:41 UTC, romvano commented
Переделал!
Я оставил тесты, которые проверяли переход по ссылкам, но добавил больше позитивных тестов на внутреннюю логику (например, добавление-удаление комментария)

2017-07-26 23:09 UTC, dkotegov commented
Принято

2017-07-26 23:09 UTC, closed without merging