HH and prod
dkotegov/homework-4 pull request #31
Opened 2017-11-26 15:57 UTC by vladpereskokov

2017-12-13 13:06 UTC, dkotegov requested changes

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/base.py
> +                assert(username == UserPage.USER_NAME1)
Похоже на костыль
Лучше открывать чистое окно, логиниться за первого пользователя и удалять, тогда try/except не нужен

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/base.py
> +                assert (username == UserPage.USER_NAME1)
И тут

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/feed.py
> +        self.user_page.logout()
Почему тест начинается с разлогина? Можно сделать отдельный suite со своим setUp

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/feed.py
> +        feed.add_like()
Если предыдущий тест не пройдет, у этого будет ложно положительное срабатывание

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/gift.py
> +        self.like_added = True
А почему like_added=True делается не в add_like()? И можно же обойтись без него

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/gift.py
> +        self.driver.refresh()
До рефреша он не пропадет? Похоже на баг

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/photo.py
> +        self.photo_deleted = True
Если delete() ничего не удалит, то тест упадет, а photo_deleted будет True, и очистка в конце тоже не произойдет

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/photo.py
> +        self.driver.implicitly_wait(0.5)
Этот implicitly_wait будет влиять на все тесты выполненные после

2017-12-13 13:06 UTC, dkotegov commented on as_check_list/tests/photo.py
> +        self.assertTrue(self.photo_page.like_counter.is_empty())
А если этот тест упадет это баг или фича? Например ОК могут сделать троттлинг на эти действия.
Что мы проверяем тут?

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/BasicTest.py
> +from page import *
Плохо импортировать *
Получите головную боль при дебаге

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/BasicTest.py
> +        self.logout() if logout else None
Зачем else?
```
if logout:
  self.logout()
```

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/events_modal_test.py
> +        self.set_marks(None, photos, marks)
Вот это всё можно вынести в setUp

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/events_modal_test.py
> +            result = None
Вместо всего if этого можно сделать один assert

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/events_modal_test.py
> +        self.assertTrue(result)
Проверки должны быть самом в тесте, а сейчас они в check_marks

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/page.py
> +            #self.driver.save_screenshot('screen_after.png')
Забыли убрать?

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/page.py
> +                    .click().perform()
В лекциях я показывал как избежать actionchains, когда элемент становится видимым только при наведении
Делайте display: block вместо display: none и весь try будет не нужен

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/page.py
> +        except:
Плохо перехватывать всё

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/page.py
> +    MARK = '//a[contains(text(), "{}")]/../../../../../../../div/div[@class="feedback_type"]/span'
Этот селектор будет нестабильным, стоит структуре чуть-чуть поменяться и он упадет

2017-12-13 13:06 UTC, dkotegov commented on es_check_list/remove_marks_test.py
> +            result = not self.check_marks(None, photos, marks, name, False)
Проверки должны быть в тестах в виде ассертов

2017-12-13 13:06 UTC, dkotegov commented on vp_check_list/tests/combine_actions_comments_test.py
> +		)
Работа с браузером должна быть в page object

2017-12-13 13:06 UTC, dkotegov commented on vp_check_list/tests/errors_tests.py
> +			self.assertEqual(1, 1)
assertTrue(True)

2017-12-13 13:06 UTC, dkotegov commented on vp_check_list/tests/xss_test.py
> +		WebDriverWait(self.driver, 10, 0.1).until(self.__alert_check__)
А проверка где?

2017-12-13 15:12 UTC, vladpereskokov commented on vp_check_list/tests/combine_actions_comments_test.py
> +		)
*Fixed*

2017-12-13 15:12 UTC, vladpereskokov commented on vp_check_list/tests/errors_tests.py
> +			self.assertEqual(1, 1)
*Fixed*

2017-12-13 15:12 UTC, vladpereskokov commented on vp_check_list/tests/xss_test.py
> +		WebDriverWait(self.driver, 10, 0.1).until(self.__alert_check__)
*Fixed*

2017-12-13 15:18 UTC, dkotegov commented
Принято

2017-12-22 11:20 UTC, dkotegov requested changes

2017-12-22 11:20 UTC, dkotegov commented on vp_check_list/tests/xss_test.py
> +			self.assertTrue(False)
Тут надо делать `raise` :)
А еще лучше вместо всего блока try оставить одну строку
```WebDriverWait(self.driver, 10, 0.1).until(self.__alert_check__)```

2017-12-22 11:20 UTC, dkotegov commented on vp_check_list/tests/errors_tests.py
> +			self.assertTrue(True)
Я имел в виду, что это антипаттерн: Проверка, которая никогда не упадет

2017-12-22 11:22 UTC, dkotegov commented
Принято

2017-12-22 11:22 UTC, closed without merging