Тесты, Поиск + Фото
dkotegov/homework-4 pull request #33
Opened 2017-11-27 16:46 UTC by aorel

Буторин http://st-jira.tech-mail.ru/browse/PARK-87
Орел http://st-jira.tech-mail.ru/browse/PARK-85

2017-12-13 13:15 UTC, dkotegov requested changes

2017-12-13 13:15 UTC, dkotegov commented on tests_butorin/photos_test.py
> +        self.add_photo()
А где проверка, что фото добавилось?

2017-12-13 13:15 UTC, dkotegov commented on tests_butorin/photos_test.py
> +        self.photos.open_photo(LOGIN, id)
А тут, что оно открылось

2017-12-13 13:15 UTC, dkotegov commented on tests_butorin/photos_test.py
> +        self.assertEqual(count, self.photos.get_photos_count() + 1)
Лучше `self.assertNotEqual(count, self.photos.get_photos_count())`

2017-12-13 13:15 UTC, dkotegov commented on tests_butorin/photos_test.py
> +        self.assertEqual(link.format(LOGIN, id), self.photos.get_link())
Зачем проверять ссылку? Что тут может сломаться?

2017-12-13 13:15 UTC, dkotegov commented on tests_orel/search_input_tests.py
> +            self.main_page.get_search_suggestions_showall_text())
Тест из одного ассерта?

2017-12-13 13:15 UTC, dkotegov commented on tests_orel/search_input_tests.py
> +        self.main_page.is_search_suggestions_on_page()
Это не тест, а констатация факта

2017-12-13 13:15 UTC, dkotegov commented on tests_orel/search_input_tests.py
> +search_input_tests = [
Это должно быть в раннере

2017-12-13 13:15 UTC, dkotegov commented on tests_orel/search_page_tests.py
> +    def test(self):
А где проверки?

2017-12-21 13:20 UTC, aorel commented
@dkotegov, посмотрите еще раз, пожалуйста.

2017-12-23 23:41 UTC, dkotegov commented on tests_butorin/photos_test.py
> +        self.added_photos.append(self.photos.get_last_photo())
А почему оно здесь, а не в заливке?

2017-12-23 23:42 UTC, dkotegov commented
Принято

2017-12-23 23:42 UTC, closed without merging