Тесты!
dkotegov/homework-4 pull request #34
Opened 2017-11-29 09:48 UTC by dondiego4697

Клюквин Артем
Чернов Андрей
Злобина Светлана
Крылов Сергей
Степанов Денис

2017-12-13 13:49 UTC, dkotegov requested changes

2017-12-13 13:49 UTC, dkotegov commented on tests/AboutPage/AboutInfoComponent.py
> +        # self._music_input_field.send_keys(text)
Почему закоментировано?

2017-12-13 13:49 UTC, dkotegov commented on tests/comment_tests.py
> +        self.assertEqual(False, comments.contains_comments())
assertFalse

2017-12-13 13:49 UTC, dkotegov commented on tests/Component/Component.py
> +            )
Для этого есть implicit wait

2017-12-13 13:49 UTC, dkotegov commented on tests/Component/Component.py
> +    def _get_element_by_xpath(self, xpath, root=None):
Внутри find_element_by_xpath уже есть ожидание, зачем добавлять еще одно?

2017-12-13 13:49 UTC, dkotegov commented on tests/ForumPage/ForumComponent.py
> +        # ActionChains(self.driver).move_to_element(del_btn).click(del_btn).perform()
?

2017-12-13 13:49 UTC, dkotegov commented on tests/MainPage/Feeling/Feeling.py
> +        feeling.click()
Вместо try лучше перед этим кликом дожидаться, что он возможен

2017-12-13 13:49 UTC, dkotegov commented on tests/MainPage/MainPage.py
> +import time
Ой

2017-12-13 13:49 UTC, dkotegov commented on tests/MainPage/Post/Post.py
> +def retry_times(func, times):
Что это и зачем?

2017-12-13 13:49 UTC, dkotegov commented on tests/MainPage/Post/Post.py
> +            pass
Почему pass? Не нашли ну и ладно?

2017-12-13 13:49 UTC, dkotegov commented on tests/comment_tests.py
> +        self.assertTrue(not comments.contains_comments())
assertFalse

2017-12-13 13:49 UTC, dkotegov commented on tests/forum_comments_tests.py
> +        discussion_frame = forum_component.add_comment()  # добавление второго комментария, на случай, если первый на самом деле не добавился, а просто текст совпал
Ну нет же! Уберите)
Если тест ложно положительно срабатывает, то это проблема в проверке, а не в том, что он один комментрий добавляет ;)

2017-12-13 13:49 UTC, dkotegov commented on tests/poll_tests.py
> +        post_form.close()
Эта строчка не выполнится, если ассерт упадет
Перенесите в tearDown

2017-12-13 13:49 UTC, dkotegov commented on tests/poll_tests.py
> +        self.assertRaises(WebDriverException, post_form.share)
А зачем проверять наличие WebDriverException?

2017-12-13 13:49 UTC, dkotegov commented on tests/poll_tests.py
> +        self._delete_last_post_from_notes()
Этому место в tearDown

2017-12-13 13:49 UTC, dkotegov commented on tests/post_manipulation_tests.py
> +        self._delete_last_post_from_notes()
И тут

2017-12-13 13:49 UTC, dkotegov commented on tests/profile_tests.py
> +        # self.assertTrue(is_contains_video)
?

2017-12-13 13:49 UTC, dkotegov commented on tests/reshare_tests.py
> +        self.assertRaises(StaleElementReferenceException, reshare_in_msg_view.visible)
И тут, зачем?

2017-12-13 13:49 UTC, dkotegov commented on tests/status_tests.py
> +    #     self.assertTrue(main_page.delete_recommended_friend())
?

2017-12-17 11:29 UTC, dondiego4697 commented on tests/AboutPage/AboutInfoComponent.py
> +        # self._music_input_field.send_keys(text)
Забыли, осталось

2017-12-17 11:37 UTC, dondiego4697 commented on tests/Component/Component.py
> +            )
implicit wait дожидается только загрузки html, если же у нас контент динамически подгружается дальше, то он уже не работает как надо

2017-12-17 11:39 UTC, Sovianum commented on tests/ForumPage/ForumComponent.py
> +        # ActionChains(self.driver).move_to_element(del_btn).click(del_btn).perform()
Делал другую реализацию, забыл выпилить. Убрал.

2017-12-17 11:42 UTC, dondiego4697 commented on tests/MainPage/MainPage.py
> +import time
ой

2017-12-17 11:42 UTC, dondiego4697 commented on tests/MainPage/MainPage.py
> +import time
он не использовался

2017-12-17 11:46 UTC, Sovianum commented on tests/MainPage/Feeling/Feeling.py
> +        feeling.click()
Согласен, но, там происходит странная ситуация: объект настроения видим, клик по нему не бросает исключения, но необходимого действия не происходит, если клик сделать слишком рано. При этом состояние элемента, при котором клик по нему приводит к необходимому действию в дом-дереве не отличается от того, когда клик уходит в никуда. Найти условие, при котором подключается js-коллбэк, мы не смогли, поэтому сделали таймаут с повтором действия.

2017-12-17 11:48 UTC, dondiego4697 commented on tests/MainPage/Post/Post.py
> +def retry_times(func, times):
какой то наркоман баловался и забыл убрать

Если действие не проходило или что-то подобное, у него было еще три попытки

2017-12-17 11:55 UTC, dondiego4697 commented on tests/comment_tests.py
> +        self.assertEqual(False, comments.contains_comments())
+

2017-12-17 11:55 UTC, Sovianum commented on tests/MainPage/Post/Post.py
> +            pass
Нет, там просто список друзей может сразу выпасть, и в этом случае мы выбираем друга прямо из него. А может не выпасть. Тогда кликаем по инпуту с выбором друга и выбираем друга из выпавшего списка.

2017-12-17 11:56 UTC, dondiego4697 commented on tests/comment_tests.py
> +        self.assertTrue(not comments.contains_comments())
\+

2017-12-17 12:04 UTC, dondiego4697 commented on tests/forum_comments_tests.py
> +        discussion_frame = forum_component.add_comment()  # добавление второго комментария, на случай, если первый на самом деле не добавился, а просто текст совпал
Справедливо

2017-12-17 12:18 UTC, dondiego4697 commented on tests/poll_tests.py
> +        post_form.close()
+

2017-12-17 12:19 UTC, dondiego4697 commented on tests/poll_tests.py
> +        self._delete_last_post_from_notes()
\+

2017-12-17 12:20 UTC, dondiego4697 commented on tests/post_manipulation_tests.py
> +        self._delete_last_post_from_notes()
\+

2017-12-17 12:22 UTC, Sovianum commented on tests/poll_tests.py
> +        self.assertRaises(WebDriverException, post_form.share)
Здесь мы проверяем, что нельзя создать опрос с одним вариантом ответа. По логике работы одноклассников пока не будут удовлетворены условия создания валидного опроса, кнопка создания опроса будет не кликабельной. Поэтому мы здесь жмем по кнопке и проверяем, что клик не прошел.

2017-12-17 12:28 UTC, dondiego4697 commented on tests/reshare_tests.py
> +        self.assertRaises(StaleElementReferenceException, reshare_in_msg_view.visible)
Единственная проверка, в зоне нашей ответственности, это посмотреть что окно с поделяшкой закрылось. Мы проверяем ленту, а так нам надо будет залезть еще и в сообщения.

2017-12-17 12:28 UTC, dondiego4697 commented on tests/profile_tests.py
> +        # self.assertTrue(is_contains_video)
\+

2017-12-17 12:28 UTC, dondiego4697 commented on tests/status_tests.py
> +    #     self.assertTrue(main_page.delete_recommended_friend())
\+

2017-12-17 12:39 UTC, Sovianum commented on tests/Component/Component.py
> +    def _get_element_by_xpath(self, xpath, root=None):
На случай, если есть элемент с совпадающим селектором в foreground и в background, мы ждем загрузки foreground, а потом ищем нужный элемент.

2017-12-23 21:07 UTC, dkotegov commented on README.md
> +    PASSWORD=qweasdzxc123
Не храните пароли в гите

2017-12-23 21:07 UTC, dkotegov commented on run_tests.py
> +        unittest.makeSuite(ProfileTests)
suite ~можно~ нужно указать через запятую
```
suite = unittest.TestSuite((
    unittest.makeSuite(StatusTests),
    unittest.makeSuite(PollTestsPositive),
    unittest.makeSuite(PollTestsNegative),
    unittest.makeSuite(CommentTests),
    unittest.makeSuite(ForumCommentsTests),
    unittest.makeSuite(AboutInfoTests),
    unittest.makeSuite(PostManipulationTests),
    unittest.makeSuite(ReshareTests),
    unittest.makeSuite(UncategorizedTests),
    unittest.makeSuite(ProfileTests),
))
result = unittest.TextTestRunner().run(suite)
sys.exit(not result.wasSuccessful())
```

2017-12-23 21:07 UTC, dkotegov commented
Принято

2017-12-23 21:07 UTC, closed without merging