first commit
dkotegov/homework-4 pull request #39
Opened 2017-12-06 16:40 UTC by FVarya

2017-12-24 00:59 UTC, dkotegov requested changes

2017-12-24 00:59 UTC, dkotegov commented on test_fedorova/group_test.py
> +from page import *
Плохо импортировать *, можно получить головную боль при дебаге

2017-12-24 00:59 UTC, dkotegov commented on test_fedorova/group_test.py
> +	while True:
Без while можно обойтись, циклов в тестах надо избегать
Если такой тест начнет моргать, отлаживать его будет очень сложно

2017-12-24 00:59 UTC, dkotegov commented on test_fedorova/group_test.py
> +	group_name = ''.join(random.choice(string.ascii_uppercase) for _ in range(5))
Копипаст можно вынести в отдельный setUp, в отдельном suite

2017-12-24 00:59 UTC, dkotegov commented on test_fedorova/page.py
> +	self.driver.find_element_by_xpath(self.NAME).send_keys(text)
Поиск элемента лучше делать отдельной переменной, а потом с ней взаимодействовать
В такой реализации, поиск будет делаться каждый раз по всей странице, это дорогая операция

2017-12-26 20:58 UTC, FVarya commented on test_fedorova/group_test.py
> +	while True:
@dkotegov 
в данном тесте я захожу в группы в рекомендованных, до тех пор пока не найду открытую группу, т.к. я не могу проверить отписку от группы, в которых требуется подтверждение администрации при вступлении.

2017-12-27 13:26 UTC, dkotegov commented on test_fedorova/group_test.py
> +	while True:
А если что-то пойдет не так? Тест зависнет.

2017-12-27 13:27 UTC, dkotegov commented on test_fedorova/group_test.py
> +	while True:
Тут нарушено атомарность, вступление и отписка должны быть двумя разными тестами, тогда циклы будут не нужны вообще. Вступаем в первую, отписываемся от захардкоженной.

2018-04-27 13:22 UTC, closed without merging