Tests done
dkotegov/homework-4 pull request #41
Opened 2017-12-18 22:41 UTC by Metalluga

Check-List:
Пользователь может
-Добавить новый альбом
-Добавить новое фото
-Удалить альбом
-Удалить фото
-Ввести в строку поиска запрос
-Перейти на полноценную страницу поиска
-Искать музыку по названию группы
-Искать музыку по названию альбома
-Искать университеты по названию
-Искать пользователей по стране
-Искать пользователей по городу
-Искать пользователей по возрасту
-Искать группы по ключевым словам
-Искать пользователей по полу

P.S. Дмитрий, здравствуйте, прошу прощения за то, что отсылаю вам работу так поздно. На лекциях было сказано, что использование циклов в тестах - антипаттерн. Когда я тестирую то, насколько корректно работает поиск с ограничениями по возрасту или поиск в конкретном городе, я предполагаю, что список пользователей будет содержать лишь тех, чей возраст или город входит в указанные рамки. Мне не приходит в голову, каким образом можно это проверить без циклов (в том или ином виде). Не предложите вариант, как от этого избавиться? Или же в данном случае использование циклов оправдано? Заранее спасибо.

2017-12-24 01:56 UTC, dkotegov requested changes

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/pages.py
> +        user_password = 'testQA1'
Не светите пароли в гите

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/pages.py
> +    REMOVE_ALBUM = '//div[@class="photo-panel __shift"]/div/div[2]/ul/li[2]/a'
Этот селектор будет не стабильным
Он упадет, если какой-то элемент в середине изменится или пропадет

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/photos_page_tests.py
> +        )
Работа с браузером должна быть в page object

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/photos_page_tests.py
> +    )),
А это должно быть в раннере

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/search_input_tests.py
> +        self.assertTrue(self.DEFAULT_SEARCH_STRING in self.driver.current_url)
`assertIn`

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/photos_page_tests.py
> +        photo_page.delete_album_confirm()
Антипаттерн
```
do_smth1()
do_smth2()
do_smth3()
```

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/search_input_tests.py
> +        self.assertEqual(self.SHOW_ALL_TEXT, self.main_page.get_search_suggestions_showall_text())
Тест из одной проверки выглядит странно, в нем должны быть какие-то действия

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/search_page_tests.py
> +        )
И тут

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/search_page_tests.py
> +        self.assertTrue(self.TEST_GROUP in unquote(encoded).decode('utf-8'))
И тут

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/search_page_tests.py
> +        self.assertTrue(number_from_result_header is not None and number_from_result_header != 0)
Если такая проверка упадет, будет ошибка "False is not True" 
Чтобы понять причину придется тест запускать еще раз под отладчиком

2017-12-24 01:56 UTC, dkotegov commented on tests_rogachev/search_page_tests.py
> +        self.assertEqual(len(result), len([s for s in result if self.TEST_COUNTRY in s.text]))
И тут

2017-12-25 18:13 UTC, Metalluga commented
Исправлено

2017-12-26 17:02 UTC, dkotegov commented on run_tests.py
> +    ]
Их можно указывать через запятую в одной TestSuite

2017-12-26 17:02 UTC, dkotegov commented on tests_rogachev/photos_page_tests.py
> +from time import sleep
Ой

2017-12-26 17:02 UTC, dkotegov commented
Принято, 10 баллов

2017-12-26 17:02 UTC, closed without merging