ДЗ4 Кирьяненко Александр
dkotegov/homework-4 pull request #44
Opened 2018-05-16 12:32 UTC by kiryanenko

## Команда
**Проект Фото**  

- Кирьяненко Александр
- Куклина Нина
- Черкасов Кирилл
- Парпибаев Артур

## Чек-лист
1. Создать альбом
2. Удалить альбом
3. Изменить название у альбома
4. Добавить "класс" к альбому
5. Отмена "класса" у альбома
6. Добавить фото к альбому
7. Добавить фото с описанием  к альбому
8. Добавить "класс" к фото
9. Отмена "класса" у фото
10. Сделать фото обложкой альбома

## Логин и пароль
    LOGIN=technopark26
    PASSWORD=testQA13

2018-05-17 22:57 UTC, dkotegov commented
Засветил пароль в гитхабе :facepalm:
А где тесты твоих коллег?

2018-05-17 23:13 UTC, dkotegov requested changes

2018-05-17 23:13 UTC, dkotegov commented on README.md
> +    PASSWORD=testQA13
:(

2018-05-17 23:13 UTC, dkotegov commented on README.md
> +*Данный чек-лист выполнил Кирьяненко Александр*
Должен быть один PR на всю команду

2018-05-17 23:13 UTC, dkotegov commented on tests/album_test.py
> +        self.auth()
Это должно быть в setUp

2018-05-17 23:13 UTC, dkotegov commented on tests/album_test.py
> +    def create_album(self, album_name='Test album #{}'.format(time.time())):
Перенеси в пейджи

2018-05-17 23:13 UTC, dkotegov commented on tests/album_test.py
> +    def like_album(self, album_name):
И это

2018-05-17 23:13 UTC, dkotegov commented on tests/album_test.py
> +        # Обновлю и еще раз проверю
Зачем?

2018-05-17 23:13 UTC, dkotegov commented on tests/album_test.py
> +        first_photo_item.click()
Работа с браузером должна быть в пейджах

2018-05-17 23:13 UTC, dkotegov commented on tests/pages/user_add_album_photo_page.py
> +        self.driver.execute_script("document.getElementById('{}').submit()".format(self.FORM))
А почему через JS?

2018-05-17 23:13 UTC, dkotegov commented on tests/pages/page.py
> +def wait_until_url_changes(method_to_decorate):
get по умолчанию ждет загрузки страницы

2018-05-17 23:13 UTC, dkotegov commented on tests/pages/user_album_page.py
> +        self.element.click()
Выглядит как костыль

2018-05-18 13:34 UTC, kiryanenko commented on tests/album_test.py
> +        # Обновлю и еще раз проверю
Чтобы на 100% быть уверенным, что в бд он был добавлен. А не просто виджет поменялся.

2018-05-18 13:38 UTC, dkotegov commented on tests/album_test.py
> +        # Обновлю и еще раз проверю
Лучше сходить в базу, если в базу доступа нет, то проверить ответ от АПИ :)
Зачем повторять то, что уже было проверено, проще сразу сделать reload и проверить один раз (но тогда я пристану к reload)

2018-05-25 16:32 UTC, dkotegov commented on tests/test_comments.py
> +        self.assertFalse(0, err)
assertFalse(False)

2018-05-25 16:56 UTC, dkotegov commented
Принято, 20 баллов

2018-05-25 16:56 UTC, closed without merging