[Crazy Coders] [Zubarev Anton]
dkotegov/homework-4 pull request #46
Opened 2018-05-16 17:10 UTC by ZubAnt

2018-05-17 23:33 UTC, dkotegov requested changes

2018-05-17 23:33 UTC, dkotegov commented on src/components/base_element.py
> +            return True
Элемента нет, возвращаем True? :D

2018-05-17 23:33 UTC, dkotegov commented on src/components/elements/gift_element.py
> +    XPATH_OWN_GIFTS_RECEIVE_NAV_SIDE_ICO = '//i[@class="tico_img ic ic_nav_gifts-receive"]'
А почему бы не выбрать один класс из трех? Будет намного стабильнее.

2018-05-18 08:58 UTC, ZubAnt commented on src/components/elements/gift_element.py
> +    XPATH_OWN_GIFTS_RECEIVE_NAV_SIDE_ICO = '//i[@class="tico_img ic ic_nav_gifts-receive"]'
Страница с подарками и страница с собственными подарками отличается выпадающим списком. 
Переменная `XPATH_OWN_GIFTS_RECEIVE_NAV_SIDE_ICO`как раз отвечает за поиск элемента в выпадающем списке. Если данный элемент присутствует на странице, значит, это страница является страницей своих подарков.
Переменная `XPATH_OWN_GIFT_NAV_SIDE_ICO` отвечает за элемент в списке nav-side. С помощью него осуществляется, собственно, переход на на страницу сових подарков со страницы подарков. Поэтому эта переменная также необходима.
А переменная `XPATH_OWN_GIFTS_NAV_SIDE` не используетсяв тестах. Изначально на нее  возлагалась задача описанной выше переменной. Но не получалось находить элемент, поэтому пошли другим путем.

2018-05-24 19:34 UTC, closed without merging