ПР от команды Сообщений
dkotegov/homework-4 pull request #47
Opened 2018-05-17 11:42 UTC by Crusader727

2018-05-18 00:49 UTC, dkotegov commented
Прогоните код через pep8

2018-05-18 01:19 UTC, dkotegov requested changes

2018-05-18 01:19 UTC, dkotegov commented on tests/pages/forms/base_element.py
> +            return True
Если элемента нет, возвращаем True?
Это чужой код :(

2018-05-18 01:19 UTC, dkotegov commented on tests/pages/forms/dialog_form.py
> +    SENT_MESSAGE_TEXT = '//div[contains(@class, "msg_tx")]/div[2]/div[1]/span[1]/span[1]'
Нестабильный селектор

2018-05-18 01:19 UTC, dkotegov commented on tests/tests.py
> +        if(self.CURRENT_DIALOG_URL[23] == 'c'):
?

2018-05-18 01:19 UTC, dkotegov commented on tests/tests.py
> +        self.CURRENT_DIALOG_URL = self.driver.current_url
А зачем тут это?

2018-05-18 01:19 UTC, dkotegov commented on tests/tests.py
> +        self.create_dialog()
Можно вынести в setUp

2018-05-18 01:19 UTC, dkotegov commented on tests/tests.py
> +        self.auth_page.chage_account(self.BOT_1_LOGIN, self.PASSWORD)
Зачем менять аккаунт, если это для tearDown, унесите в него

2018-05-18 01:19 UTC, dkotegov commented on tests/tests.py
> +    #     self.assertTrue(not self.dialog_page.exsistance_of_pinned_message(), "test_unpin_message failed")
assertFalse, а почему закомменчено?

2018-05-18 01:19 UTC, dkotegov commented on tests/tests.py
> +        self.dialog_page.block_user()
Если ассерт упадет, эта строчка не выполнится

2018-05-18 01:19 UTC, dkotegov commented
Функциональных действий и проверок мало, практически все тесты одинаковые

2018-05-18 06:08 UTC, Crusader727 commented on tests/pages/forms/base_element.py
> +            return True
Код мой! Если он был и в другом месте -  меня попросили и я скинул в общий чат. Если кто-то его в наглую переписал я не виноват.

2018-05-18 06:13 UTC, Crusader727 commented on tests/pages/forms/base_element.py
> +            return True
Объяснение: staleness_of - возвращает тру если элемента нет в доме(он дождался этого). Если выпал эксепшн , значит элемент не найден, значит по аналогии тру.

2018-05-18 06:13 UTC, Crusader727 commented on tests/pages/forms/base_element.py
> +            return True
В этом месте эксепшн падает только из EC.presence_of_element_located.

2018-05-18 06:19 UTC, Crusader727 commented on tests/tests.py
> +        if(self.CURRENT_DIALOG_URL[23] == 'c'):
Этим мы проверяем чат групповой или личный. Подумали, что это самый простой и 100% рабочий метод.

2018-05-18 06:20 UTC, Crusader727 commented on tests/tests.py
> +        self.CURRENT_DIALOG_URL = self.driver.current_url
Сохраняем урл текущего чата, чтоб почистить за собой потом.

2018-05-18 06:26 UTC, Crusader727 commented on tests/tests.py
> +    #     self.assertTrue(not self.dialog_page.exsistance_of_pinned_message(), "test_unpin_message failed")
Случайно вышло.

2018-05-18 11:17 UTC, dkotegov commented on tests/pages/forms/base_element.py
> +            return True
Зачем так сложно? Он всегда будет отрабатывать за таймаут, используйте until_not

2018-05-24 14:16 UTC, dkotegov commented
Большинство тестов не запускается, посмотрите внимательно на свой раннер 
И в работе куча закомментированого кода

2018-05-24 14:18 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +            "test_delete_sticker_pack failed")
assertFalse

2018-05-24 14:19 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +        self.dialog_page.uninstall_stickers_set(set_id1)
Если добавление не сработает, удалять будет нечего и тест пройдет

2018-05-24 14:20 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +from time import sleep
Неиспользуемый импорт ;)

2018-05-24 14:27 UTC, dkotegov commented on tests/pages/dialog.py
> +        if(self.attach_form.get_loader()):
Зачем этот if? Если он не выполнится, то фото не отправится

2018-05-24 14:33 UTC, dkotegov commented on tests/pages/dialog_menu.py
> +        if (attach_form.existence_ready_photo_button()):
И тут

2018-05-24 14:37 UTC, dkotegov commented on tests/pages/forms/base_element.py
> +            return True
Все еще не понимаю смысла этой конструкции
Сначала ждем элемент с таймаутом в 10 сек, потом ждем что он исчез 10 секунд и если этого не произошло, ловим Timeout Exception, и все равно считаем, что всё хорошо
Получается что оба исхода ведут к одинаковому результату, зачем тогда это здесь?

2018-05-24 14:41 UTC, dkotegov commented on tests/pages/forms/dialog_form.py
> +            "{AppID}", app_id)
format же

2018-05-24 14:43 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +        self.delete_dialog()
Если в тесте диалог не создастся, то здесь он не удалится и tearDown упадет, окно не закроется
То есть при любом упавшем тесте окно останется висеть

2018-05-24 14:45 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +            "test_send_heart_sticker failed")
Все стикеры можно проверить в одном тесте

2018-05-24 14:47 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +            "testing stickers set already exists")
Тест еще не начался, уже ассерт, это как?
Начальное состояние должно гарантироваться setUp и tearDown, не нужно подтыкать тесты ассертами на проверку начального состояния

2018-05-24 14:49 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +        self.dialog_page.install_stickers_set(set_id)
В конце этого тесты стикеры устанавливаются, это значит, что если его поменять местами с предыдущим тестом, оба упадут. Это неправильно, тесты не должны зависеть от порядка запуска.

2018-05-24 14:51 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +            "test_sticker_bar failed")
Скрытие бара, а потом проверка что он остался?

2018-05-24 14:52 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +            "test_sticker_bar failed")
А зачем? Это же повторение предыдущего теста?

2018-05-24 14:52 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +            "test_send_symbols_smile failed")
Тоже самое, что и со стикерами, это один тест

2018-05-24 14:54 UTC, dkotegov commented on tests/suites/test_send_stickers.py
> +            "test_send_sticker_x2_from_bar failed")
Что проверяет этот тест? Что тут может сломаться при том, что остальные тесты пройдут? Похоже на повторение того, что уже протестировано раньше

2018-05-24 14:54 UTC, dkotegov commented on tests/suites/tests_find_dialog_msg.py
> +from time import sleep
И тут

2018-05-24 14:55 UTC, dkotegov commented on tests/suites/tests_find_dialog_msg.py
> +            self.message_page.get_found_message_text())
Есть подозрение что этот ассерт всегда будет проходить, потому что если текст не совпадает, упадет предыдущая строчка

2018-05-24 14:56 UTC, dkotegov commented on tests/suites/tests_group_dialogs.py
> +        self.leave_group_chat()
Если выйти не получится окно останется висеть

2018-05-24 14:58 UTC, dkotegov commented on tests/suites/tests_group_dialogs.py
> +        confirm_page.confirm()
После этого теста в tearDown произойдет повторный выход, который по логике упадет, потому что выходить неоткуда

2018-05-24 15:34 UTC, dkotegov requested changes

2018-05-24 15:34 UTC, dkotegov commented on tests/suites/tests_group_dialogs.py
> +        self.driver.refresh()
А зачем refresh? Похоже на костыль

2018-05-24 15:34 UTC, dkotegov commented on tests/suites/tests_send_messages.py
> +        self.dialog_page.reject_game_invite(app_id)
Похоже на предыдущий тест

2018-05-24 15:34 UTC, dkotegov commented on tests/suites/tests_send_messages.py
> +        self.dialog_page.reject_game_invite(app_id)
И тут, в чем разница с предыдущими?

2018-05-24 15:34 UTC, dkotegov commented on tests/suites/two_accaunts_management.py
> +    #         "test_report_unicode_message failed")
Почему закомментировано?

2018-05-24 15:34 UTC, dkotegov commented on tests/suites/two_accaunts_management.py
> +        self.NEED_TO_BLOCK_USER = True
Лучше перенести эту строчку выше, потому что если межу unblock и `NEED_TO_BLOCK_USER = True` что-то упадет, то будет `False`

2018-05-24 19:30 UTC, Crusader727 commented on tests/suites/test_send_stickers.py
> +        self.delete_dialog()
Диалог создается не в тесте, а в сетапе.

2018-05-24 19:42 UTC, Crusader727 commented on tests/suites/test_send_stickers.py
> +            "test_sticker_bar failed")
Тут тест на работоспособность кнопок хайд и шоу(типо закрыли, потом открыли - можно еще раз закрыть)

2018-05-24 19:50 UTC, Crusader727 commented on tests/suites/tests_group_dialogs.py
> +        confirm_page.confirm()
Это не тест)

2018-05-24 19:54 UTC, Crusader727 commented on tests/suites/tests_group_dialogs.py
> +        self.driver.refresh()
Это случайно)

2018-05-24 19:57 UTC, Crusader727 commented on tests/suites/two_accaunts_management.py
> +        self.NEED_TO_BLOCK_USER = True
Справедливо

2018-05-24 20:02 UTC, Crusader727 commented on tests/pages/forms/dialog_form.py
> +            "{AppID}", app_id)
/run_tests.py:43:80: E501 line too long (84 > 79 characters)
что мне с этим делать?

2018-05-24 20:07 UTC, Crusader727 commented on tests/suites/test_send_stickers.py
> +            "test_send_heart_sticker failed")
Можно же не равно нужно  😭 😭 😭 :shipit::shipit:

2018-05-24 20:10 UTC, Crusader727 commented on tests/suites/tests_find_dialog_msg.py
> +            self.message_page.get_found_message_text())
Тут вроде все 🔥🔥🔥

2018-05-24 20:12 UTC, Crusader727 commented on tests/suites/tests_group_dialogs.py
> +        self.leave_group_chat()
А как тогда выйти, чтоб оно не висело?

2018-05-24 20:14 UTC, Crusader727 commented on tests/suites/tests_send_messages.py
> +        self.dialog_page.reject_game_invite(app_id)
Согласен👌

2018-05-25 14:50 UTC, dkotegov commented
Принято, 20 баллов

2018-05-25 14:50 UTC, closed without merging