Пападык Всеволод
dkotegov/homework-4 pull request #48
Opened 2018-05-17 14:01 UTC by sevaTechoPark

2018-05-18 00:47 UTC, dkotegov requested changes

2018-05-18 00:47 UTC, dkotegov commented on tests/Auth/AuthForm.py
> +    PASSWORD1 = os.environ.get('PASSWORD1', 'testQA1')
Ну блин!

2018-05-18 00:47 UTC, dkotegov commented on tests/Lilbs/Lib.py
> +            expected_conditions.visibility_of_element_located((By.XPATH, x_path)))
А зачем игнорить NoSuchElementException?

2018-05-18 00:47 UTC, dkotegov commented on tests/Lilbs/Lib.py
> +    def check_exist_element(driver, x_path):
Видимо not_exist

2018-05-18 00:47 UTC, dkotegov commented on tests/Main/CenterMenu.py
> +    WALL_TOOLBAR = '//div[@id="mainContentLeftColumn"]//div[@id="hook_Block_SideNavigation"]//div[@data-l="t,navigation"]//a[@data-l="t,userPage"]'
Этот селектор будет очень нестабильным

2018-05-18 00:47 UTC, dkotegov commented on tests/Main/Feed.py
> +    LIKE_BUTTONS = '//div[@class="feed-list"]//div[@class="feed-w"]//ul[@class="widget-list"]//li[@class="widget-list_i "][last()]'
И этот

2018-05-18 00:47 UTC, dkotegov commented on tests/Main/Feed.py
> +    LIKE_PANEL_LAST_LIKED_LINKS = LIKE_PANEL + '//li[@class="u-menu_li"]//ul[@class="ucard-mini-list __redesign __react"]//li[@class="ucard-mini-list_li"]//a'
Слишком много элементов

2018-05-18 00:47 UTC, dkotegov commented on tests/Main/Feed.py
> +        if self.get_number_emotion() != 5:
А зачем этот if?

2018-05-18 00:47 UTC, dkotegov commented on tests/Main/Feed.py
> +            reaction_number = randint(0, 4)
Рандом тут не оправдан

2018-05-18 00:47 UTC, dkotegov commented on tests/example_test.py
> +        print "save nicknames complete"
Дебажные принты надо убрать

2018-05-18 00:47 UTC, dkotegov commented on tests/example_test.py
> +        cls.save_nicknames()
Зачем? Похоже на отдельный тест

2018-05-18 00:47 UTC, dkotegov commented on tests/example_test.py
> +        self.assertEqual(True, top_menu.check_notification_close(), "close notification fail")
assertTrue

2018-05-18 00:47 UTC, dkotegov commented on tests/example_test.py
> +        self.auth_user()
Для этого есть setUp

2018-05-18 00:47 UTC, dkotegov commented on tests/example_test.py
> +        feed.remove_like()
А почему тут только remove, где добавление?

2018-05-18 00:47 UTC, dkotegov commented on tests/example_test.py
> +                self.assertTrue(True)
Серьезно?

2018-05-18 00:50 UTC, dkotegov commented
А где остальные члены команды?

2018-05-26 20:34 UTC, dkotegov requested changes

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Album.py
> +    random_album_name = '%dalbum%d' % (randint(1,9999),randint(1,9999))
Рандом тут не нужен

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Album.py
> +        url = self.driver.find_element_by_css_selector('[data-l="t\,selectCurrentUser"]').get_attribute('href') + '/photos'
А почему не клик по ссылке?

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Album.py
> +        self.jsClick(self.driver.find_element_by_css_selector(self.create_album_btn_css))
Использовать ВЕЗДЕ js клики это костыль, используйте нативные клики

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Album.py
> +    album_name_css = '[class="form__gl-1-2 form photo-album-settings"] [type="text"]'
Константы капсом, прогоните код через pep8

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +        self.assertTrue(album_component.random_album_name in album_component.get_albums(), "Album not created")
Ну нет, развертите в ассерты без циклов
Если в середине цикла оно упадет, вы не узнаете на каком именно шаге, а отладить не сможете, потому что рандом
P.S. assertIn

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Auth.py
> +    email_field = '/html//input[@id="field_email"]'
Есть подозрение, что `/html` тут не нужен

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +        PASSWORD = "testQA1"
:(

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +                           0, "Wrong login or password")
Этот ассерт должен быть в отдельном тесте на авторизацию в отдельном suite

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +        if self.driver.find_elements_by_css_selector('.stub-img__user24-female').__len__() > 0:
Избавьтесь от всех if-ов в тестах, тут явно должно быть 2 теста вместо одного (или несколько проверок в одном)

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +        authForm.submit()
Копипаста из теста в тест, уберите авторизацию в setUp

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +            '.user-settings .user-settings_i:nth-of-type(6) .user-settings_i_tx').text
Вся работа с браузером должна быть в PageObject

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +        self.assertTrue(inactive_language.lower() == active_language.lower(), "Language haven't changed")
assertEqual

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Gender.py
> +        isChecked = self.driver.execute_script('return document.getElementById("field_gender_1").checked')
Не понял зачем здесь этот if? Вы не знаете начальное состояние? Это значит тесты за собой не убирают :)

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Gender.py
> +        self.driver.execute_script("document.getElementById('%s').checked = true" % _id)
Переделайте на нативный клик

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Group.py
> +        return True
Кнопку не нашли,  ну и ладно? :)

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Note.py
> +    default_note_text = "Random note %d %d %d" % (randint(0,100),randint(0,100),randint(0,100))
И тут рандом не нужен

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Note.py
> +        self.driver.find_elements_by_css_selector("div")
find который потом никак не используется? Просто замедлите тест :(

2018-05-26 20:34 UTC, dkotegov commented on tests/Main/Note.py
> +            self.driver.find_element_by_css_selector(self.user_url_css).get_attribute("href") + '/statuses')
Тут тоже должен быть клик

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
>  from tests.constants.Constants import *
Не ваш код

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +                self.assertTrue(True)
?!

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +        group_component.fill_search()
Тестовые данные должны быть в тестах, а не пейджах

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +            like_component.likes_count), "like error!")
Почему -1?
P.S. assertEqual
И лучше переписать его на несколько строчек, не ленитесь

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +        self.driver.refresh()
Зачем refresh?

2018-05-26 20:34 UTC, dkotegov commented on tests/example_test.py
> +            '#hook_Loader_UserStatusesMRBLoader .feed:nth-of-type(1) .media-text_cnt').text
И тут

2018-05-26 20:38 UTC, sevaTechoPark commented on tests/example_test.py
> +        authForm.submit()
нельзя, мы под двумя пользователями авторизуемся

2018-05-26 20:41 UTC, dkotegov commented on tests/example_test.py
> +        authForm.submit()
Можно, сделайте логин/пароль параметрами

2018-05-28 18:35 UTC, devasidmi commented on tests/example_test.py
> +        self.driver.refresh()
Чтобы проверить, создалась заметка действительно или нет, а не просто создать типа, а потом удалить

2018-06-04 16:38 UTC, dkotegov requested changes

2018-06-04 16:38 UTC, dkotegov commented on tests/Lilbs/Lib.py
> +        ignored_exceptions = (StaleElementReferenceException,)
А это зачем игнорить?

2018-06-04 16:38 UTC, dkotegov commented on run_tests.py
> +#!/usr/bin/env python2
У всех разный env

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Album.py
> +    ALBUM_NAME_CSS = '[class="form__gl-1-2 form photo-album-settings"] [type="text"]'
Тут лучше выбрать один класс

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Album.py
> +    EDIT_ALBUM_CSS = "div[class='photo-menu_edit iblock-cloud_show'] a"
и тут

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Album.py
> +    NEW_ALBUM_NAME = 'test'
Тестовые данные должны быть в тесте

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/CenterMenu.py
> +        self.driver.execute_script("arguments[0].scrollIntoView();", element)
А зачем 3 разных wait перед этим действием? Почему бы сразу не сделать последний?

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Feed.py
> +        return 6
Не увидел ответа на вопрос "зачем", поэтому эти if-ы надо разобрать

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +            self.assertTrue(nickname == UsersName.second_account_name)
Если здесь проверка на конкретный nickname, тогда зачем получать ВСЕ ссылки через get_all_links?

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +            main_page.open()
А почему бы не кликнуть?

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +            if names[i] == UsersName.first_account_name:
Костыль

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Friend.py
> +            'return document.querySelectorAll("%s")' % self.PENDING_FRIENDS_CSS)
Почему через JS?

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Friend.py
> +        while len(self.PENDING_FRIENDS) < self.OUTGOING_FRIENDS_COUNT:
Что это? Зачем?

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Friend.py
> +                'return document.querySelectorAll("%s")' % self.PENDING_FRIENDS_CSS)
?

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Friend.py
> +        self.jsClick(cancel_btn[-1])  # Здесь он нужен
Зачем?

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Gender.py
> +    def set_start_gender(self):
Костыль, потому что вы не знаете начального состояния

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Gender.py
> +    def get_current_gender(self):
А в чем отличие от set_start_gender тогда?

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Group.py
> +    URL_CSS = "//div[@id='gs_result_list']/div[1]//a[@title]"
Нестабильный селектор

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Group.py
> +            pass
Ищем элемент, если не нашли, ну и ладно?

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Group.py
> +        if len(self.driver.find_element_by_xpath(self.FIRST_GROUP_XPATH).find_elements_by_css_selector(self.JOIN_BTN_CSS)) == 0:
Разбейте на несколько строк

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Language.py
> +    LANGUAGE_ELEMENT_CSS = '.user-settings .user-settings_i:nth-of-type(6) .user-settings_i_lk'
И тут

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Language.py
> +        self.jsClick(changeBtn)  # Здесь он нужен
Если нужен, объясняйте зачем

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Language.py
> +        return Lib.simple_wait_element_css(self.driver, self.ACTIVE_LANGUAGE).text
Ну и это унесите в либу, раз сделали её

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Like.py
> +        self.jsClick(like_btn)  # Здесь он нужен
?

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Like.py
> +        self.LIKES_COUNT = like_btn.get_attribute(self.DATA_COUNT)
Это переменная

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Message.py
> +        self.DIALOG_ID = el.get_attribute('href').split("/")[-1]
И это переменная

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/Theme.py
> +            2].find_element_by_css_selector("a")
Не разрывайте квадратные скобки :(
P.S. 2 - magic number

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/TopMenu.py
> +        '//button[@data-l="t,btn_ignore"]'
Ужасно нестабильные селекторы

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/TopMenu.py
> +            pass
Ждем элемент, если не дождались, ну и ладно ;)

2018-06-04 16:38 UTC, dkotegov commented on tests/Main/TopMenu.py
> +            pass
И тут

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        # cls.driver.quit()
Почему закомменчено?

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +    def create_notification(self):
Это должно быть в пейджах

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +    def create_like(self):
И это

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +    def open_user_wall(self):
И это

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +                NOTIFICATION_TABS_TITLE[i], title, "select notification tabs")
Разбейте for на плоские ассерты и на несколько тестов, если нужно

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +            REPORT_SUCCESS, top_menu.place_first_notification(), "report notification fail")
Тестовые данные должны быть в тестах

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +                        "close notification fail")
Антипаттерн, все проверки должны быть в тестах

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        self.assertEquals(5, feed.get_number_emotion(), "remove reaction fail")
magic number

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +            any(UsersName.second_account_name in s for s in names), "second user not found")
Разберите for, any
На крайний случай есть assertIn

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +                continue
Костыль

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +            self.assertTrue(nickname == UsersName.second_account_name)
assertEqual

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +            any(UsersName.second_account_name in s for s in names), "second user not found")
И тут

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        self.driver.refresh()
?

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        album_component.delete_album()
Если ассерт упадет, альбом не удалится

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +                           0, "Wrong login or password")
Это должно быть в отдельном сьюте с прописанными шагами

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        friend_component.cancel_request()
Если ассерт упадет, эта строка не выполнится

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        self.assertTrue(profile_component.get_current_gender(),
А почему тут не сравнение старого и нового?
Проверки должны быть внутри тестов

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        self.assertFalse(group_component.getFollowBtn(), "Follow group error")
И всё? Проверить эту фичу можно только по отсутствующей кнопке?

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +                         active_language.lower(), "Language haven't changed")
Видимо notEqual?

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        self.assertEqual(likes_from_btn_by_owner, likes_count, "like error!")
Предположите случай, когда тест упадет? У меня ощущение, что этот тест всегда будет проходить.

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        self.assertEqual(messageComponent.DEFAULT_MESSAGE,
Тестовые данные должны быть внутри теста

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        self.driver.refresh()
Страница после добавления обновляться не должна, и это не значит, что надо самим это делать
Вместо этого дерните АПИ и посмотрите, что новая заметка приходит в АПИ и отображается в интерфейсе

2018-06-04 16:38 UTC, dkotegov commented on tests/example_test.py
> +        self.assertNotEqual(themeForm.START_THEME_NAME,
И тут

2018-06-04 16:47 UTC, devasidmi commented on tests/Main/Friend.py
> +        while len(self.PENDING_FRIENDS) < self.OUTGOING_FRIENDS_COUNT:
Ой, тут была вообще жесть. Если открываешь страницу, у тебя вроде 19 отправок, а показывает сначала 10! Т.е мне нужно проскролить и получить уже все, я максимально долго тупил, почему не все приходит....

2018-06-04 16:47 UTC, devasidmi commented on tests/Main/Friend.py
> +                'return document.querySelectorAll("%s")' % self.PENDING_FRIENDS_CSS)
Ой, тут была вообще жесть. Если открываешь страницу, у тебя вроде 19 отправок, а показывает сначала 10! Т.е мне нужно проскролить и получить уже все, я максимально долго тупил, почему не все приходит....

2018-06-04 17:11 UTC, dkotegov commented on tests/Main/Friend.py
> +                'return document.querySelectorAll("%s")' % self.PENDING_FRIENDS_CSS)
Ну это же не повод тесты костылить, откуда там 19 отправок кстати?

2018-06-12 10:00 UTC, dkotegov requested changes

2018-06-12 10:00 UTC, dkotegov commented on tests/example_test.py
> +         self.assertTrue(audio.add_audio())
Проверки должны быть в самом тесте

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/AudioAdd.py
> +        before_click =  Lib.visibility_wait_element(self.driver, "//div[@class ='mml_notif mml_notif__num __on']").text
Селектор вынеси в константы, так не понятно что это за элемент и почему ты его ищешь

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/AudioAdd.py
> +        return (after_click > before_click)
Это похоже на тест

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/BlackList.py
> +        return Lib.check_exist_element(self.driver, self.MAN_IN_BLACKLIST)
Проверка после которой ничего не делается, зачем она здесь?

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/CommentClass.py
> +        else:return False
Не экономь на переносах строк) Так не пишут)

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/CommentClass.py
> +        return Lib.check_exist_element(self.driver, self.COMMENT)
И тут

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/CreateChanel.py
> +        Lib.simple_set_text_to_element(self.driver, self.INPUT_BLOCK,"test")
Тестовые данные должны быть в самом тесте

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/CreateChanel.py
> +        return False
И этот надо перенести в тесты

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/CreateChanel.py
> +        if after_click <= before_click:return False
И тут

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/Events.py
> +        Lib.simple_set_text_to_element(self.driver, self.TEXT_INPUT,"What about your diplom ?")
И тут

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/Interview.py
> +    FIRST_INPUT = "//div[@class='posting_poll h-mod ok-posting-handler']//descendant::div[4]//descendant::textarea"
Очень нестабильный селектор, упадет при малейшем изменении сайта

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/Interview.py
> +    SECOND_INPUT = "//div[@class='posting_poll h-mod ok-posting-handler']//descendant::div[6]//descendant::textarea"
И этот

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/Interview.py
> +        Lib.simple_set_text_to_element(self.driver, self.SECOND_INPUT,"Of Course")
И здесь

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/Interview.py
> +        return True
Это уже тест

2018-06-12 10:00 UTC, dkotegov commented on tests/Main/Mood.py
> +    INPUT_TEXT = "End testing OK"
И тут

2018-06-12 10:00 UTC, dkotegov commented on tests/example_test.py
> +        self.assertTrue(black_man.check_in_blacklist())
do_smth()

2018-06-12 10:00 UTC, dkotegov commented on tests/example_test.py
> +        else:self.assertTrue(False)
assertTrue(False)? Серьзно?

2018-06-12 10:02 UTC, dkotegov requested changes

2018-06-12 10:02 UTC, dkotegov commented on tests/Main/Share.py
> +         return Lib.check_exist_element(self.driver,check_share)
Отступ 4 пробела

2018-06-12 10:02 UTC, dkotegov commented on tests/Main/Relations.py
> +         return Lib.check_exist_element(self.driver,"//input[@checked]")
И тут отступ

2018-06-13 15:49 UTC, devasidmi commented on tests/Main/Language.py
> +        self.jsClick(changeBtn)  # Здесь он нужен
1) Если ждать пока элемент появится, кидается ошибка, что элемент не появился.
2) Если просто искать, то не находит
И это везде, где я писал, что jsClick мой нужен. Соответсвенно проблемы решаются моим методом, а в остальных местах где он был лишним, я все поправил

2018-06-16 09:48 UTC, devasidmi commented on tests/example_test.py
> +                         active_language.lower(), "Language haven't changed")
Здесь как раз Equal, если они равны, то должна вернуться ошибка

2018-06-16 10:00 UTC, devasidmi commented on tests/example_test.py
> +        self.assertFalse(group_component.getFollowBtn(), "Follow group error")
Можно API дернуть...

2018-06-16 10:30 UTC, devasidmi commented on tests/example_test.py
> +        album_component.delete_album()
Так, если ассерт упадет, то нечего удалять:)

2018-06-16 10:33 UTC, devasidmi commented on tests/example_test.py
> +        friend_component.cancel_request()
Тут аналогично, если ассерт падает, то значит мы не отправили запрос в друзья, т.е нам не нужно его отменять :)

2018-06-16 10:57 UTC, devasidmi commented on tests/Main/Theme.py
> +            2].find_element_by_css_selector("a")
Это не мы, это все PEP8 :)

2018-06-16 11:03 UTC, devasidmi commented on tests/Main/Friend.py
> +                'return document.querySelectorAll("%s")' % self.PENDING_FRIENDS_CSS)
Видимо кто-то не чистил до нас...

2018-06-16 11:06 UTC, devasidmi commented on tests/Main/Gender.py
> +    def set_start_gender(self):
Я считаю, что тест Gender.py хороший, потому что:
1) Я получаю текущее значение, а не тупо дефолтно 0 или 1
2) Я всегда за собой чищу, т.е если кто-то до меня поменял и не вернул назад - окей, я меня, проверяю и обратно возвращаю

2018-06-16 11:14 UTC, devasidmi commented on tests/Main/Friend.py
> +                'return document.querySelectorAll("%s")' % self.PENDING_FRIENDS_CSS)
Не понимаю почему это костыль... Костыль это очищать 19 заявок и тестит свою одну, а так я написал тест, который работает, даже если разработчики пофигисты и не чистят за собой

2018-06-16 16:12 UTC, devasidmi commented on tests/Main/Gender.py
> +    def get_current_gender(self):
Исправил set_start_gender

2018-06-20 20:04 UTC, devasidmi commented on tests/Main/Friend.py
> +        self.jsClick(cancel_btn[-1])  # Здесь он нужен
1. Если ждать пока элемент появится, кидается ошибка, что элемент не появился.
2. Если просто искать, то не находит
И это везде, где я писал, что jsClick мой нужен. Соответсвенно проблемы решаются моим методом, а в остальных местах где он был лишним, я все поправил

2018-06-23 17:37 UTC, sevaTechoPark commented on tests/example_test.py
> +        cls.save_nicknames()
потому для уведомлений я захожу под двумя аккаунтами, и один аккаунт создает уведомления другому. Для стабильной работы, нужно обрабатывать уведомление именно от второго пользователя, это достигается проверкой имени. Таким образом, этот метод запоминает имена обоих пользователей, что используется для уведомлений

2018-06-23 17:41 UTC, sevaTechoPark commented on tests/example_test.py
> +            if names[i] == UsersName.first_account_name:
ищу созданное мной уведомление

2018-06-23 17:44 UTC, sevaTechoPark commented on tests/example_test.py
> +                continue
ищу созданное мной уведомление

2018-06-23 17:49 UTC, sevaTechoPark commented on tests/example_test.py
> +    def create_notification(self):
просто избежать дублирование кода, действия выполняются в пейджах

2018-06-23 17:49 UTC, sevaTechoPark commented on tests/example_test.py
> +    def open_user_wall(self):
и это

2018-06-23 17:54 UTC, sevaTechoPark commented on tests/example_test.py
> +            main_page.open()
согласен можно было кликнуть, но это же не ошибка?

2018-06-25 17:22 UTC, dkotegov commented
Ладно

2018-06-25 17:22 UTC, closed without merging