Никита Куликов
dkotegov/homework-4 pull request #50
Opened 2018-05-25 10:23 UTC by LionZXY

Сделанные тесты:
 - При скролле до конца списка на странице списка видео, подгружается новая порция видео (если в данном списке больше видео, чем вмещается в одну порцию)
 - Можно добавить видео к себе, оно попадает в список «Отложенное видео»
 - После просмотра видео, оно попадает в список «История просмотра»
 - При удалении видео оно исчезает из списка «Моё видео»
 - Можно писать в чат сбоку от видео
 - Можно получить ссылку на видео, по ней открывается страница с видео
 - Можно поставить лайк видео, убрать лайк
 - Можно прикрепить видео к личному сообщению
 - При нажатии вкладок разделы переключаются
 - Поиск видео работает
 - Видео открывается
 - Стрим открывается
 - Можно оставить комментарий к стриму
 - Можно оставить комментарий к видео
 - Видео загружается, После загрузки видео попадает в вкладку "Моё видео"
 - Подписаться на канал, в моих подписках видео каналов, на которые ты подписан

Отдельно постарался потестировать тест-кейс "Можно прикрепить к посту видео":
 - Можно добавить видео к посту через диалог и опубликовать его (со смайлом)
 - Можно добавить видео к посту через диалог и опубликовать его (со смайлом и текстом)
 - Можно добавить видео к посту через диалог и опубликовать его (с текстом)
 - Можно добавить видео к посту через диалог и опубликовать его (без текста)
 - Можно удалить прикрепленное видео в меню добавления поста
 - К посту можно прикрепить несколько видео
 - К посту можно прикрепить видео через кнопку "Видео" в блоке "Напишите заметку", можно прикрепить уже загруженное на сайт видео, видео по ссылке
 - Можно прикрепить видео к посту
 - Можно загрузить видео с внешнего источника (напр. YouTube) к блоку поста

2018-05-25 18:18 UTC, dkotegov requested changes

2018-05-25 18:18 UTC, dkotegov commented on pages/video_list.py
> +        # clicking the button that is wrapped into hidden elements like a freaking chicken roll TODO: maybe refactor
Серьезно?

2018-05-25 18:18 UTC, dkotegov commented on pages/wall.py
> +                not_open = False
Дикий костыль

2018-05-25 18:18 UTC, dkotegov commented on tests/video.py
> +        self.driver.refresh()
Почему тест начинается с перезагрузки страницы?

2018-05-25 18:18 UTC, dkotegov commented on tests/video.py
> +        wall_post.post()
Тест без ассертов

2018-05-25 18:18 UTC, dkotegov commented on tests/video.py
> +        for i in range(expected_video_count):
От этого можно избавиться

2018-05-25 18:18 UTC, dkotegov commented on tests/video.py
> +        self.assertTrue(added_video_count == expected_video_count)
asserEqual

2018-05-25 18:18 UTC, dkotegov commented on tests/video.py
> +        self.assertFalse(before_video_id == after_video_id)
assertNotEqual

2018-05-25 18:18 UTC, dkotegov commented on tests/video.py
> +        video_page.scroll_videos_to(1000000)
Костыль

2018-05-25 18:18 UTC, dkotegov commented on tests/video.py
> +                         "Not equals: {0} + 1 != {1}".format(initial_count, second_count))
Если этот ассерт упадет, то код дальше не выполнится

2018-05-25 18:19 UTC, dkotegov commented
Принято, 10 баллов Олегу и 10 баллов Никите

2018-05-25 18:19 UTC, closed without merging

2018-06-28 06:30 UTC, LionZXY commented
Править ошибки тут как мёртвому давать таблетки от головной боли... Надо полностью переписать