Группы 2
dkotegov/homework-4 pull request #54
Opened 2018-06-13 12:51 UTC by kgulyy

### Команда 
- Константин Гулый
- Ольга Сурикова

2018-06-14 23:50 UTC, dkotegov requested changes

2018-06-14 23:50 UTC, dkotegov commented on Components/component.py
> +    def is_exist_element(self, xpath):
Тут лучше без wait, потому что когда элемента нет, оно отработает за таймаут и не будет отличаться от простого поиска элемента, который тоже упадет

2018-06-14 23:50 UTC, dkotegov commented on Components/component.py
> +    def is_not_exist_element(self, xpath):
Вместо этого будет `not is_exist_element`

2018-06-14 23:50 UTC, dkotegov commented on Components/component.py
> +        self.find_element(xpath).click()
Костыль, любой клик будет с wait, для этого придумали неявные ожидания

2018-06-14 23:50 UTC, dkotegov commented on Components/component.py
> +    def find_element(self, xpath):
Implicit wait спасет мир

2018-06-14 23:50 UTC, dkotegov commented on Components/component.py
> +        input_element.send_keys(text)
Тоже похоже на костыль, send_keys установит фокус и удалит содержимое перед вводом

2018-06-14 23:50 UTC, dkotegov commented on tests/create_catalog_tests.py
> +        self.shop.remove()
Если удаление не сработает, окно останется висеть открытым

2018-06-14 23:50 UTC, dkotegov commented on tests/create_catalog_tests.py
> +        self.assertTrue(is_exist_catalog_stub)
А в чем разница с предыдущим тестом?

2018-06-14 23:50 UTC, dkotegov commented on tests/create_catalog_tests.py
> +        self.assertEqual(u'Название каталога не должно превышать 50 знаков', error_message)
Подозреваю, что негативные тесты на тексты об ошибках можно объединить

2018-06-14 23:50 UTC, dkotegov commented on tests/create_catalog_tests.py
> +        self.create_and_check_empty_catalog(catalog_popup, name)
А где ассерты?

2018-06-14 23:50 UTC, dkotegov commented on tests/create_catalog_tests.py
> +        self.assertTrue(is_not_exist_catalog_stub)
По логике теста лучше использовать assertFalse

2018-06-14 23:50 UTC, dkotegov commented on tests/create_catalog_tests.py
> +        self.test_create_several_catalogs(100)
Тест, в котором запускается другой тест, который запускает другой тест...

2018-06-14 23:50 UTC, dkotegov commented on tests/create_catalog_tests.py
> +        self.create_and_check_catalog_with_image('image_4K.gif')
Ну нет, что это за тесты из одной строки, их надо вынести в отдельный suite, со своим отдельным setUp и tearDown

2018-06-14 23:50 UTC, dkotegov commented on tests/create_remove_shop_test.py
> +        self.assertEqual(number_of_groups_before, number_of_groups_after)
Есть смысл тогда проверить assertNotEqual перед удалением

2018-06-14 23:50 UTC, dkotegov commented on tests/create_remove_shop_test.py
> +    def get_current_number_of_groups(self):
Это должно быть не в тестах, чтобы можно было переиспользовать

2018-06-14 23:50 UTC, dkotegov commented on tests/create_topic_test.py
> +    def test_create_topic(self):
И всё? Один тест?

2018-06-14 23:50 UTC, dkotegov commented on tests/edit_catalog_tests.py
> +        self.assertEquals(self.CATALOG_NAME, catalog_name_before_edit)
Если есть тест на создание, это уже можно не проверять

2018-06-14 23:50 UTC, dkotegov commented on tests/edit_catalog_tests.py
> +        other_catalog_name = u'Другой каталог'
Константа, заглавными буквами

2018-06-14 23:50 UTC, dkotegov commented on tests/products_tests.py
> +            self.test_add_product(product_name, product_price, i)
И тут

2018-06-14 23:50 UTC, dkotegov commented on tests/remove_catalog_tests.py
> +        self.driver.refresh()
А зачем?

2018-06-15 07:58 UTC, kgulyy commented on Components/component.py
> +    def is_exist_element(self, xpath):
Согласен, исправил)

2018-06-15 08:06 UTC, kgulyy commented on Components/component.py
> +    def is_not_exist_element(self, xpath):
Есть

2018-06-15 08:07 UTC, kgulyy commented on Components/component.py
> +        self.find_element(xpath).click()
Исправляюсь)

2018-06-15 08:11 UTC, kgulyy commented on Components/component.py
> +    def find_element(self, xpath):
Действительно спас)

2018-06-15 09:01 UTC, kgulyy commented on Components/component.py
> +        input_element.send_keys(text)
Согласен, очистка используется по факту только в одном кейсе, поднял на абстракцию выше.

2018-06-15 10:58 UTC, kgulyy commented on tests/create_catalog_tests.py
> +        self.shop.remove()
Согласен, но есть отдельный [тест](https://github.com/kgulyy/homework-4/blob/5ccbcc5e4a66e473d629d3380dd668866d925e03/tests/create_remove_shop_test.py#L20]), который проверяет создание и удаление магазина (shop).

2018-06-15 11:04 UTC, kgulyy commented on tests/create_catalog_tests.py
> +        self.assertTrue(is_exist_catalog_stub)
Разные кнопки, но схожая логика, объединил в один тест.

2018-06-15 11:36 UTC, kgulyy commented on tests/create_catalog_tests.py
> +        self.assertEqual(u'Название каталога не должно превышать 50 знаков', error_message)
Объединил в один тест.

2018-06-15 13:05 UTC, kgulyy commented on tests/create_catalog_tests.py
> +        self.create_and_check_catalog_with_image('image_4K.gif')
Поправил, заодно хороший рефакторинг получился)

2018-06-15 13:35 UTC, kgulyy commented on tests/create_topic_test.py
> +    def test_create_topic(self):
Этот тест не входит непосредственно в чек-лист и нужен для включения в setUp класса [TopicHashTagsTests](https://github.com/kgulyy/homework-4/blob/5ccbcc5e4a66e473d629d3380dd668866d925e03/tests/topic_hashtag_tests.py#L12) создание топика.

2018-06-15 13:35 UTC, kgulyy commented on tests/edit_catalog_tests.py
> +        other_catalog_name = u'Другой каталог'
Исправил

2018-06-15 16:16 UTC, kgulyy commented on tests/products_tests.py
> +            self.test_add_product(product_name, product_price, i)
Все константы переведены в верхний регистр.

2018-06-15 16:19 UTC, kgulyy commented on tests/remove_catalog_tests.py
> +        self.driver.refresh()
По факту счетчик продуктов обновляется и виджеты продуктов удаляются только после перезагрузки страницы.

2018-06-15 16:23 UTC, kgulyy commented on tests/edit_catalog_tests.py
> +        self.assertEquals(self.CATALOG_NAME, catalog_name_before_edit)
Согласен, исправил)

2018-06-15 16:38 UTC, kgulyy commented on tests/create_remove_shop_test.py
> +    def get_current_number_of_groups(self):
Исправил)

2018-06-15 16:41 UTC, kgulyy commented on tests/create_remove_shop_test.py
> +        self.assertEqual(number_of_groups_before, number_of_groups_after)
Ок, добавил

2018-06-15 17:35 UTC, kgulyy commented on tests/create_catalog_tests.py
> +        self.assertTrue(is_not_exist_catalog_stub)
Исправил

2018-06-15 21:32 UTC, kgulyy commented on tests/create_catalog_tests.py
> +        self.test_create_several_catalogs(100)
Исправил

2018-06-15 21:33 UTC, kgulyy commented on tests/create_catalog_tests.py
> +        self.create_and_check_empty_catalog(catalog_popup, name)
Провел рефакторинг - исправил)

2018-06-15 22:11 UTC, kgulyy commented
Все исправил и прокомментировал)

2018-06-16 21:59 UTC, dkotegov commented
Принято

2018-06-16 21:59 UTC, closed without merging