RK6 Cooperation
dkotegov/homework-4 pull request #56
Opened 2018-11-21 19:19 UTC by PDmitryA

### В команде:

Гарифуллин Тимур
http://jira.bmstu.cloud/browse/QA-86
Мигранов Рустам
http://jira.bmstu.cloud/browse/QA-72
Парпибаева Надежда
http://jira.bmstu.cloud/browse/QA-82
Попонкин Дмитрий
http://jira.bmstu.cloud/browse/QA-89

_логин и пароль в tg._

2018-11-22 13:10 UTC, dkotegov requested changes

2018-11-22 13:10 UTC, dkotegov commented on tests/components/write_letter.py
> +        while try_again:
Потенциально вечный цикл

2018-11-22 13:10 UTC, dkotegov commented on tests/Garifullin/folder_with_subdir_delete.py
> +        self.driver.quit()
Если любое из действий выше упадет, то окно не закроется

2018-11-22 13:10 UTC, dkotegov commented on tests/Garifullin/folder_with_subdir_delete.py
> +    def setUp(self):
Все действия с браузером должны быть внутри PageObject

2018-11-22 13:10 UTC, dkotegov commented on tests/Garifullin/folder_with_subdir_delete.py
> +        sidebar.click_by_folder(self.FOLDER_NAME_CHILD)
Весь этот блок можно заменить несколькими строчками, это реализация и должно быть не в тестах

2018-11-22 13:10 UTC, dkotegov commented on tests/Garifullin/locked_folder_delete.py
> +        sidebar.click_block_folder()
Атомарность нарушена, и поэтому столько копипасты

2018-11-22 13:10 UTC, dkotegov commented on tests/Garifullin/folder_with_subdir_delete.py
> +        folder_create.click_select_parent_inbox()
Похоже на часть теста уже

2018-11-22 13:10 UTC, dkotegov commented on tests/Garifullin/folder_with_subdir_delete.py
> +    def test_delete_folder_with_subdir(self):
А почему всего один тест?

2018-11-22 13:10 UTC, dkotegov commented on tests/Garifullin/locked_folder_delete.py
> +    def test_delete_locked_folder(self):
Зачем выносить это в отдельный файл?

2018-11-22 13:10 UTC, dkotegov commented on tests/Garifullin/locked_folder_delete.py
> +        folder_create.set_password(self.FOLDER_PASSWORD)
И это тоже уже тест

2018-11-22 13:10 UTC, dkotegov commented on tests/components/sidebar.py
> +        self.driver.refresh()
Зачем рефреш? Никакого действия перед ним нет

2018-11-22 13:10 UTC, dkotegov commented on tests/components/write_letter.py
> +        '//div[contains(concat(" ", normalize-space(@class), " "), " cke_widget_editable ")]'
Если есть contains, то зачем concat с пробелами?

2018-11-22 15:26 UTC, diarmind commented on tests/components/write_letter.py
> +        '//div[contains(concat(" ", normalize-space(@class), " "), " cke_widget_editable ")]'
потому что cke_widget_editable с простым contains найдёт и класс abc123_cke_widget_editable

2018-11-22 15:29 UTC, PDmitryA commented on tests/components/write_letter.py
> +        while try_again:
Поставить счётчик попыток? Это в принципе бага, что оно не сохраняется с первого раза. Насколько целесообразно лечить симптомы? 

p.s. Зарепортил это

2018-11-23 01:30 UTC, dkotegov requested changes

2018-11-23 01:30 UTC, dkotegov commented on tests/Garifullin/locked_folder_delete.py
> +        folder_unlock.submit()
Вот это надо утащить в PageObject

2018-11-23 01:30 UTC, dkotegov commented on tests/Poponkin/draft_create_test.py
> +    def testAdditionsFromUser(self):
А где ассерты?)

2018-11-23 01:30 UTC, dkotegov commented on tests/QA_72_Migranov/by_right_mouse_button_click.py
> +        self.sidebar.delete_folder(self.SOURCE_DIR_NAME)
Костыль

2018-11-23 01:30 UTC, dkotegov commented on tests/QA_72_Migranov/test.py
> +        #     print("Exception has been thrown. " + str(ex))
?

2018-11-23 01:30 UTC, dkotegov commented on tests/components/letters.py
> +        except:
Плохо перехватывать всё

2018-11-23 01:30 UTC, dkotegov commented on tests/components/write_letter.py
> +        '//div[contains(concat(" ", normalize-space(@class), " "), " cke_widget_editable ")]'
Тогда выбери другой селектор

2018-11-23 01:30 UTC, dkotegov commented on tests/components/write_letter.py
> +        while try_again:
Не целесообразно

2018-11-23 01:30 UTC, dkotegov commented on tests/pages/main_page.py
> +    def redirectToQa(self):
Похоже на просто open()

2018-11-23 16:54 UTC, PDmitryA commented on tests/components/write_letter.py
> +        '//div[contains(concat(" ", normalize-space(@class), " "), " cke_widget_editable ")]'
abc123_cke_widget_editable - класс для примера, на самом деле такого нет. пробелы нужны для того, чтобы сравнивать на соответствие классов, быть уверенным в выборе класса.

2018-11-23 16:55 UTC, dkotegov commented on tests/components/write_letter.py
> +        '//div[contains(concat(" ", normalize-space(@class), " "), " cke_widget_editable ")]'
Это костыль

2018-11-23 17:31 UTC, PDmitryA commented on tests/components/write_letter.py
> +        while try_again:
Тогда я убираю счётчик вообще, верно? И тест тем и хорош, что падает?)

2018-11-23 19:59 UTC, InfantryMan commented on tests/QA_72_Migranov/by_right_mouse_button_click.py
> +        self.sidebar.delete_folder(self.SOURCE_DIR_NAME)
Мне тогда в создании папки необходимо проверять, создана ли на данный момент уже такая папка? И если создана, то ничего не делать?

2018-11-23 20:00 UTC, InfantryMan commented on tests/QA_72_Migranov/test.py
> +        #     print("Exception has been thrown. " + str(ex))
Уберу

2018-11-27 19:05 UTC, dkotegov commented on tests/QA_72_Migranov/by_right_mouse_button_click.py
> +        self.sidebar.delete_folder(self.SOURCE_DIR_NAME)
Если папка есть до теста, это значит, что предыдущий за собой не очистил

2018-11-27 19:09 UTC, dkotegov commented on tests/components/write_letter.py
> +        while try_again:
Ну есть смысл написать тест, который будет падать и выключить его из основного прогона, пока не пофиксят
Например скипнуть его с пометкой что падает из-за бага и ссылку на репорт

2018-11-27 19:58 UTC, InfantryMan commented on tests/QA_72_Migranov/by_right_mouse_button_click.py
> +        self.sidebar.delete_folder(self.SOURCE_DIR_NAME)
Мне получается не надо проверять, что предыдущий за собой не очистил?

2018-11-27 20:07 UTC, dkotegov commented on tests/QA_72_Migranov/by_right_mouse_button_click.py
> +        self.sidebar.delete_folder(self.SOURCE_DIR_NAME)
Нет, окружение должно быть одинаковым каждый раз
В крайнем случае можно проверить и упасть, но уж точно не исправлять его
Лучше всего будет доработать очищение в tearDown предыдущих тестов

2018-11-28 08:03 UTC, InfantryMan commented on tests/QA_72_Migranov/by_right_mouse_button_click.py
> +        self.sidebar.delete_folder(self.SOURCE_DIR_NAME)
Понял, спасибо за ответ

2018-12-20 13:45 UTC, dkotegov commented
Принято

2018-12-20 13:45 UTC, closed without merging