IT-Berries - Filtering rules
dkotegov/homework-4 pull request #58
Opened 2018-11-22 18:49 UTC by puchninanastya

2018-11-23 02:00 UTC, dkotegov requested changes

2018-11-23 02:00 UTC, dkotegov commented on pages/pages.py
> +    LETTER_FLAG = '")]/./../../../../div[@class="b-datalist__item__flag"]/div[@title="Снять флажок"]'
Если какой-нибудь элемент в середине изменится или пропадет, то селектор упадет

2018-11-23 02:00 UTC, dkotegov commented on pages/pages.py
> +    FILTERING_RULES = '//div[@class="b-nav__item"][7]'
Почему именно 7? ;)

2018-11-23 02:00 UTC, dkotegov commented on pages/pages.py
> +        if elem.is_displayed():
Если элемент невидим, то клик не пройдет, подозреваю, что этот if не нужен

2018-11-23 02:00 UTC, dkotegov commented on run_tests.py
> +    #filter_example = unittest.TestLoader().loadTestsFromTestCase(CreateFilterExample)
?

2018-11-23 02:00 UTC, dkotegov commented on steps/steps.py
> +        pass
Нигде не используется

2018-11-23 02:00 UTC, dkotegov commented on tests/changeFilterTests.py
> +        self.assertEqual(check_filter_work.check_if_letter_not_exists('Рассылки', self.TEST_1_SUBJECT), True)
assertTrue

2018-11-23 02:00 UTC, dkotegov commented on tests/changeFilterTests.py
> +        change_filter.delete()
Унесите в tearDown

2018-11-23 02:00 UTC, dkotegov commented on tests/changeFilterTests.py
> +        except:
Плохо перехватывать всё

2018-11-23 02:00 UTC, dkotegov commented on tests/changeFilterTests.py
> +        self.driver.execute_script("window.scrollTo(0, 200)")
Это должно быть в пейджах

2018-11-23 02:00 UTC, dkotegov commented on tests/changeFilterTests.py
> +    def test_change_add_condition_and_send_notification(self):
Ни одного ассерта в тесте

2018-11-23 02:00 UTC, dkotegov commented on tests/changeFilterTests.py
> +        # delete filter in USERMAIL_2 account
Очистку в tearDown, подготовку в setUp

2018-11-23 02:00 UTC, dkotegov commented on tests/createFilterExample.py
> +    '''
???

2018-12-20 13:01 UTC, dkotegov commented on tests/config.py
> +USEREMAIL_1 = 'it-berries'
так добавьте сюда @mail.ru вместо того чтобы потом `USEREMAIL_1 + '@mail.ru'` не делать ;)

2018-12-20 13:01 UTC, dkotegov commented on tests/changeFilterTests.py
> +        change_filter.delete()
Если ассерт упадет, фильтр не удалится

2018-12-20 13:05 UTC, dkotegov requested changes

2018-12-20 13:05 UTC, dkotegov commented on pages/pages.py
> +    LETTER_FLAG = '")]/./../../../../div[@class="b-datalist__item__flag"]/div[@title="Снять флажок"]'
?

2018-12-20 13:05 UTC, dkotegov commented on pages/pages.py
> +                #elem.click()
?

2018-12-20 13:05 UTC, dkotegov commented on steps/steps.py
> +            except:
Не перехватывайте всё

2018-12-20 13:05 UTC, dkotegov commented on steps/steps.py
> +            try:
Ну и зачем тут try, пусть падает если не получится

2018-12-20 13:05 UTC, dkotegov commented on support/waiter.py
> +            #print "Page is ready!"
?

2018-12-20 13:05 UTC, dkotegov commented on support/waiter.py
> +            print "Loading took too much time! Locator is " + locator
Вместо принта должен быть exception

2018-12-20 13:05 UTC, dkotegov commented on support/waiter.py
> +            print "Loading took too much time! Locator is " + locator
И тут

2018-12-20 13:05 UTC, dkotegov commented on tests/changeFilterTests.py
> +        self.driver.quit()
Если какой-то из шагов выше упадет, то окно не закроется

2018-12-20 13:05 UTC, dkotegov commented on tests/changeFilterTests.py
> +        self.assertTrue(check_filter_work.check_if_letter_not_exists(Folder.NEWSLETTERS, self.TEST_1_SUBJECT))
Проверки должны быть в тестах, а не где-то еще

2018-12-20 15:21 UTC, puchninanastya commented on tests/config.py
> +USEREMAIL_1 = 'it-berries'
В некоторых местах используется только логин без 'mail.ru'. Например, при входе в почту.

2018-12-20 15:22 UTC, puchninanastya commented on steps/steps.py
> +            except:
Пофиксили

2018-12-20 15:33 UTC, puchninanastya commented on support/waiter.py
> +            #print "Page is ready!"
Комменты удалили

2018-12-20 15:33 UTC, puchninanastya commented on support/waiter.py
> +            print "Loading took too much time! Locator is " + locator
Теперь exception!

2018-12-20 17:28 UTC, dkotegov commented on pages/pages.py
> +            print('here')
удоли

2018-12-20 18:02 UTC, dkotegov commented
Принято

2018-12-20 18:02 UTC, closed without merging