RHA
dkotegov/homework-4 pull request #59
Opened 2018-11-22 20:06 UTC by supreme2302

2018-11-23 02:20 UTC, dkotegov requested changes

2018-11-23 02:20 UTC, dkotegov commented on components/base_form.py
> +    # DESTINATION_INPUT = '//div[@class="contactsContainer--3RMuQ"]/div/label/div/div/input'
?

2018-11-23 02:20 UTC, dkotegov commented on components/base_form.py
> +            print 'destination email is set'
Дебажные принты надо убрать

2018-11-23 02:20 UTC, dkotegov commented on components/base_form.py
> +            print 'no  close msg sent button'
Зачем этот try? Если вылетит exception пусть тест падает

2018-11-23 02:20 UTC, dkotegov commented on components/file_attaching_form.py
> +        #     print 'unable to send keys to input'
?

2018-11-23 02:20 UTC, dkotegov commented on components/file_attaching_form.py
> +        except Exception, e:
Плохо перехватывать всё

2018-11-23 02:20 UTC, dkotegov commented on components/file_attaching_form.py
> +        # TODO разобраться, почему проверят так долго!
Ага, разберитесь ;)

2018-11-23 02:20 UTC, dkotegov commented on components/letter_formatting_form.py
> +    TEXT_MARGIN_INC = '//div[@class="cell--3K4W6"]/div[9]/div[2]/div/div[2]'
Если какой-то элемент поменяется или пропадет, то селектор упадет

2018-11-23 02:20 UTC, dkotegov commented on components/letter_formatting_form.py
> +        ActionChains(self.driver).key_up(Keys.LEFT_SHIFT).perform()
Почему через action chains а не через sendkeys?

2018-11-23 02:20 UTC, dkotegov commented on components/letter_formatting_form.py
> +        ActionChains(self.driver).key_up(Keys.RIGHT).perform()
Keys.RIGHT * 5

2018-11-23 02:20 UTC, dkotegov commented on components/letter_functions_form.py
> +# coding=utf-8
?

2018-11-23 02:20 UTC, dkotegov commented on tests/attach_tests/attach_tests.py
> +        self.assertEqual(self.file_attaching_form.checkMessageSent(), True)
assertTrue

2018-11-23 02:20 UTC, dkotegov commented on tests/attach_tests/attach_tests.py
> +        self.assertEqual(self.file_attaching_form.check_loaded_through_cloud() is not None, True)
assertIsNotNone

2018-11-23 02:20 UTC, dkotegov commented on tests/attach_tests/attach_tests.py
> +        assert (self.file_attaching_form.check_loaded(filename=self.TEST_FILE_XLSX))
:(

2018-11-23 02:20 UTC, dkotegov commented on tests/attach_tests/attach_tests.py
> +        #     # """
?!

2018-11-23 02:20 UTC, dkotegov commented on tests/letter_formatting_tests.py
> +    def test(self):
godlike!

2018-11-23 02:20 UTC, dkotegov commented
Ребята, ревьюйте друг друга!

2018-12-04 07:48 UTC, HimmelSpark commented
Пофиксили

2018-12-20 13:28 UTC, dkotegov requested changes

2018-12-20 13:28 UTC, dkotegov commented on components/file_attaching_form.py
> +        except Exception:
Не перехватывайте всё

2018-12-20 13:28 UTC, dkotegov commented on components/letter_formatting_form.py
> +    LINK_BUTTON = '(//div[@data-test-id="editor-toolbar"]//button[@data-test-id="button"])[13]'
Очень нестабильный селектор из-за [13]

2018-12-20 13:28 UTC, dkotegov commented on components/letter_functions_form.py
> +            .until(lambda driver: driver.find_element_by_xpath(self.TEMPLATE_MARK_SAVE))
А зачем такой маленький wait? похоже на "чтобы было, хуже не станет"

2018-12-20 13:28 UTC, dkotegov commented on run_tests.py
> +# TODO комментьте чужие тесты, если не хотите страдать! 😇
Так `TODO: страдать` или `TODO: не страдать`? ;)

2018-12-20 13:28 UTC, dkotegov commented on tests/attach_tests/attach_tests.py
> +# from selenium.webdriver import ActionChains
?

2018-12-20 13:28 UTC, dkotegov commented on tests/letter_formatting_tests.py
> +    def test(self):
?!
Разбейте тест на несколько пожалуйста, он у меня в 4 экрана не влез

2018-12-20 13:28 UTC, dkotegov commented on tests/letter_functions/functions_tests.py
> +        # self.functions_form.click_cancel_button()
?

2018-12-20 13:28 UTC, dkotegov commented on tests/letter_functions/functions_tests.py
> +        # self.functions_form.click_cancel_button()
?

2018-12-20 13:28 UTC, dkotegov commented on tests/letter_functions/functions_tests.py
> +        # self.functions_form.click_cancel_button()
?

2018-12-20 13:29 UTC, dkotegov commented
Пофиксили, но не всё

2018-12-20 16:58 UTC, dkotegov commented
Принято

2018-12-20 16:58 UTC, closed without merging