Домашняя работа (Колотовкин Максим)
dkotegov/homework-4 pull request #60
Opened 2018-11-22 20:23 UTC by maxim218

Домашняя работа (Колотовкин Максим)

2018-11-22 20:30 UTC, maxim218 commented
Чеклист:
1) Валидация формы авторизации
2) Валидация формы добавления пользователей
3) Добавление новых пользователей
4) Чтение списков пользователей

2018-11-23 00:57 UTC, dkotegov requested changes

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +	#time.sleep(2)
?

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +from selenium.webdriver.support import expected_conditions as EC
Убери неиспользуемые импорты

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +		self.assertEqual(v1, v2)
?!

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +driver = webdriver.Firefox()
А где chrome?

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +print("Clear content and add users test:")
Дебажные принты нужно убрать

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +def get(s):
s - плохое название

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +get("dropContentPanelShowBtn").click()
Почитай про PageObject

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +tryAddUser("20", "maxim", "123", "addUserAlert", "Добавление пользователя прошло успешно.", "Add user 1 text OK")
И про xUnit...

2018-11-23 00:57 UTC, dkotegov commented on formsValidate.py
> +	finally:
Вместо этого должен быть ассерт

2018-11-23 00:57 UTC, dkotegov commented on formsValidate.py
> +		WebDriverWait(driver, 5).until (EC.text_to_be_present_in_element((By.ID, 'alertBox'), waitMessage))
Не нужно это оборачивать в try, если оно падает, значит в программе баг

2018-11-23 00:57 UTC, dkotegov commented on addingUsers.py
> +driver.close()
Если любая строчка выше упадет, то окно не закроется

2018-11-23 00:57 UTC, dkotegov commented on formsValidate.py
> +driver = webdriver.Firefox()
Нужно использовать Remote

2018-11-23 00:57 UTC, dkotegov commented on formsValidate.py
> +	pass
Код, который ничего не делает, зачем?

2018-11-23 00:57 UTC, dkotegov commented on test.sh
> +python3 formsValidate.py && python3 addingUsers.py && echo "  " && echo "Tests OK"
Тесты надо запускать не так

2018-12-20 00:04 UTC, maxim218 commented
Доделал тестирование

Чеклист:
	1.	Валидация формы входа в кабинет и авторизация
	2.	Валидация формы добавления пользователей и добавление пользователей
	3.	Валидация формы добавления физ.ресурсов и добавление физ.ресурсов
	4.	Получение физических ресурсов
	5.	Возврат физических ресурсов
	6.	Смена темы оформления

2018-12-20 12:55 UTC, dkotegov requested changes

2018-12-20 12:55 UTC, dkotegov commented on tests/admin_sources_adding_tests.py
> +        self.src_form.submit()
Много копипасты, в каждом тесте этот блок повторяется
Написал бы функцию, и из тестов просто вызывай с параметрами

2018-12-20 12:55 UTC, dkotegov commented on tests/pages/admin_page.py
> +            print "no alert with accept"
Принтов не должно быть

2018-12-20 12:55 UTC, dkotegov commented on tests/pages/admin_page.py
> +        try:
А зачем try? Пусть падает, это же будет баг

2018-12-20 12:55 UTC, dkotegov commented on tests/pages/admin_page.py
> +        return "Источник успешно добавлен."
Это должно быть константой, а не функцией

2018-12-20 12:55 UTC, dkotegov commented on tests/admin_users_adding_tests.py
> +        self.assertEqual(alert_text.encode('utf-8'), self.user_form.get_empty_login_msg())
encode унеси в alert_text, а msg вытащи константой в тест
Это тестовые данные, они должны быть в тесте

2018-12-20 12:55 UTC, dkotegov commented on tests/pages/component.py
> +        try:
И тут

2018-12-20 12:55 UTC, dkotegov commented on tests/pages/page.py
> +    def alert_accept(self):
Копипаста

2018-12-20 12:55 UTC, dkotegov commented on tests/user_office_color_theme_tests.py
> +import random
Неиспользуемый импорт

2018-12-20 17:39 UTC, maxim218 commented
Поправил ваши замечания.

2018-12-20 17:54 UTC, maxim218 commented
Убрал копипаст alert-ов

2018-12-20 18:14 UTC, dkotegov commented
Ладно

2018-12-20 18:14 UTC, closed without merging