Troom Troom
dkotegov/homework-4 pull request #64
Opened 2019-11-14 19:52 UTC by Pickausernaame

2019-11-15 00:26 UTC, dkotegov requested changes

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/EXPORTING_VARS.sh
> +export TEST_PASS=1QA2wsx
Ох, не храните пароли в git :(

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/anonimazer.py
> +        captcha = self._driver.find_element_by_xpath("/html/body/div[7]/div/div[2]/div/div[3]/form/div[4]/div/div[2]/div[1]/div/img")
Если какой-то элемент изменится или пропадет, селектор упадет

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/tests.py
> +        print("Driver is ready")
Дебажных принтов быть не должно

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/anonimazer.py
> +            print("No such Element")
Зачем перехватывать и ничего не делать?

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/tests.py
> +        self.assertEqual(True, self.anonimazer.is_pop_up_open())
assertTrue

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/tests.py
> +        self.assertEqual(False, self.anonimazer.is_pop_up_open())
assertFalse

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/tests.py
> +        self.assertIsNot(c1, c2)
assertNotEqual?

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/tests.py
> +#        self.assertEqual(False, self.anonimazer.is_delete_pop_up_open())
?

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/tests.py
> +        self.assertEqual(self.comment, self.anonimazer.get_comment())
Положите тестовые данные в тест

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/tests.py
> +        self.anonimazer.create_new_email()
Эти 2 строчки везде повторяются, можно унести в setUp

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/anonimazer.py
> +        elem = self._driver.find_element_by_css_selector('button[type=submit]')
Этот селектор можно вынести в константу

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/anonimazer.py
> +        elem = self._wait_visibility('input[name=Password]')
Используйте более понятные названия :)
Здесь понятно что за элемент по селектору, а если нет?

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/anonimazer.py
> +        elem = self._driver.find_element_by_xpath("/html/body/div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div/div[6]/div[2]/div[2]/div[1]/div[2]/div[3]/div[2]/div[1]/button")
Тут умер котенок

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/anonimazer.py
> +        elem = self._driver.find_element_by_xpath("/html/body/div[7]/div/div[2]/div/div[3]/form/div[6]/div[2]/button")
И тут

2019-11-15 00:26 UTC, dkotegov commented on anonimazer/anonimazer.py
> +        children_elems[0].send_keys(email)
Детей можно выбрать через селектор

2019-11-18 21:33 UTC, evvfebruary commented
Доброй ночи!  Посидели, плотно поревьюили, как смогли ( еще раз ), небольшое описание релиза.
1. Вынесли тестовые данные в ```setUp``` из переменных среды ( оставили там только BROWSER ( как просили в блоге ) и пароли ( прокидываются локально, чтобы было секьюрно) )
2. Подобрали везде валидные ```asserts``` методы ( чуть не споткнулись на ```assertIsNot``` и ```assertNotEqual``` ) 
3. Вынесли селекторы в переменные ( не все из них используется несколько раз, но мы на упреждение )
4. Погладили оставшихся в живых котят, сказали чтобы не волновались.
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/42819131/69095615-bef52b80-0a63-11ea-814d-79d976e5f34a.png">

Пацаны из TroomTroom x Технопарк Mail.Ru Group, 2019 (c)

2019-12-18 03:06 UTC, dkotegov commented
Принято

2019-12-18 03:06 UTC, closed without merging