K1ola from BADgers
dkotegov/homework-4 pull request #67
Opened 2019-11-17 15:10 UTC by K1ola

2019-12-17 21:30 UTC, dkotegov requested changes

2019-12-17 21:30 UTC, dkotegov commented on pages/auth_page.py
> +        self.driver.find_element_by_css_selector(self.LOGIN).send_keys(login)
Получается два раза ищете элемент, можно после первого поиска его сохранить и в следующей строчке использовать

2019-12-17 21:30 UTC, dkotegov commented on pages/default_page.py
> +    def wait_redirect(self, url = None):
Это уже есть в хелперах ;)

2019-12-17 21:30 UTC, dkotegov commented on pages/default_page.py
> +        self.driver.implicitly_wait(5)
Лучше устанавливать в самом начале

2019-12-17 21:30 UTC, dkotegov commented on pages/userinfo_page.py
> +from helpers import *
Плохо импортировать *
Можно получить головную боль при дебаге

2019-12-17 21:30 UTC, dkotegov commented on pages/userinfo_page.py
> +    YEAR_INPUT_CHILD = 'select[name="BirthYear"] option[value="1997"]'
Похоже на хардкод, лучше сделать параметром к методу выбора года

2019-12-17 21:30 UTC, dkotegov commented on pages/userinfo_page.py
> +        self.driver.execute_script('''window.open("https://e.mail.ru/settings?result=ok&afterReload=1","_blank");''')
Интересный выбор
Можно просто селениумом второе окно открыть

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        auth_page.authorize()
Повторяется в каждом тесте -> значит можно запихнуть в setup

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.get_town_selector()
Похоже на антипаттерн, а где ассерты? :)

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        self.assertEqual(self.driver.current_url, new_window_url)
Бесполезный тест, не надо проверять переходы по ссылкам

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.get_cancel_avatar_button()
В чеклисте написано, что проверяются все форматы, а тут одна картинка :(
P.S. Загрузку вижу, а проверки, что оно успешно загрузилось нет :)

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        self.assertEqual(old_surname_value, new_surname_value)
Лучше вместо
```python
new_surname_value = userinfo_form.get_surname_value()
self.assertEqual(old_surname_value, new_surname_value)
```
Вот так 
`self.assertNotEqual(old_surname_value, new_surname_value)`

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_page.open()
На самом деле тоже бесполезный тест, потому что тут страница перезагружается и сохранения нет
Получается, если кнопка не работает, вы об этом не узнаете
Такой тест будет всегда проходить
assertTrue(True)

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form = userinfo_page.form
Зачем второй раз?

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.save()
А если тест упадет как будете отлаживать?
Рандом никуда не сохраняется, ассертов нет, трейс не поможет
Придется запускать 100500 раз пока еще раз не повезет ;)

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.save()
А если не загрузилось тест пройдет :)

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +    def test_logout(self):
Лучше назвать по-другому, вводит в заблуждение

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.refresh_page()
Интересно, а без рефреша позволит сохранить что-нибудь?
Странный тест, с тем же успехом можно было второе окно не открывать, а рефрешить первое

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.save()
Никаких проверок, что сохранилось именно то, что вводили

2019-12-17 21:30 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.wait_for_help()
:(

2019-12-17 21:59 UTC, Betchika99 commented on tests/userinfo_test.py
> +        userinfo_form = userinfo_page.form
После нажатия кнопки Сохранить, нас редиректит на другую страницу. Нам нужно вернуться на нашу тестируемую страничку. А зачем второй раз нужно форму получить, потому что иначе у нас в переменной `user_info` лежит указатель на старую форму старой страницы, которая удалена. Надо получить новую

2019-12-17 23:13 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form = userinfo_page.form
Хорошо

2019-12-18 19:16 UTC, K1ola commented on tests/userinfo_test.py
> +        userinfo_form.get_cancel_avatar_button()
Это тест не на форматы картинок, а на проверку отображения окна кадрирования фотографии с кнопками “Сохранить” и “Отменить” при загрузке аватарки.

2019-12-18 23:09 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.get_cancel_avatar_button()
Тогда исправьте чеклист :)

2019-12-19 02:37 UTC, iamfrommoscow commented on tests/userinfo_test.py
> +        userinfo_form.refresh_page()
Этот тест рассчитан на автоматическую проверку выхода из первой вкладки, в случае если пользователь вышел из второй вкладки. Перезагружается не та вкладка, из которой пользователь выходил.

2019-12-19 02:44 UTC, dkotegov commented on tests/userinfo_test.py
> +        userinfo_form.refresh_page()
Я понимаю, это бесполезный тест
Разлогиниться на основной вкладке и обновить страницу полностью равнозначно

2019-12-19 09:07 UTC, Betchika99 commented on pages/userinfo_page.py
> +        self.driver.execute_script('''window.open("https://e.mail.ru/settings?result=ok&afterReload=1","_blank");''')
можно, но зачем :) `execute` порой надежнее

2019-12-19 15:40 UTC, dkotegov commented
Принято

2019-12-19 15:40 UTC, closed without merging