Рахимгалиев Темирлан Dwadauna
dkotegov/homework-4 pull request #71
Opened 2019-11-17 20:23 UTC by rakhimgaliyev

2019-12-18 01:02 UTC, dkotegov commented
Тесты падают:
```
d:homework-4 (master) d.kotegov$ python run_tests.py
....EE.......
======================================================================
ERROR: test_newQuestionEditTest (tests.AskTests.AskTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskTests.py", line 140, in test_newQuestionEditTest
    self.page.check_edit_time()
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskPage.py", line 166, in check_edit_time
    lambda d: d.find_element_by_class_name('q-edit-control')
  File "/Library/Python/2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:


======================================================================
ERROR: test_notEmptyQuestion (tests.AskTests.AskTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskTests.py", line 55, in test_notEmptyQuestion
    self.assertEqual(self.page.getAlertUnderQuestion(),
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskPage.py", line 57, in getAlertUnderQuestion
    alert = self.driver.find_element_by_class_name('z1LfJpugzE39YVXERE-f__0')
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".z1LfJpugzE39YVXERE-f__0"}
  (Session info: chrome=79.0.3945.88)


----------------------------------------------------------------------
Ran 13 tests in 81.892s

FAILED (errors=2)
```

2019-12-18 01:38 UTC, dkotegov requested changes

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.quitDriver()
можно сразу self.driver.quit()

2019-12-18 01:38 UTC, dkotegov commented on tests/AskPage.py
> +        self.driver.find_elements_by_class_name('login-row')[2].find_elements_by_css_selector('*')[5].click()
Если какой-то элемент изменится или пропадет, то селектор упадет

2019-12-18 01:38 UTC, dkotegov commented on tests/AskPage.py
> +    def checkUrl(self):
Проверки должны быть в тесте

2019-12-18 01:38 UTC, dkotegov commented on tests/AskPage.py
> +            # lambda d: d.find_element_by_xpath('//button[@name="submit_btn"]').click()
?

2019-12-18 01:38 UTC, dkotegov commented on tests/AskPage.py
> +        self.setQuestionAdditional(u"Собственно говоря, если греческий салат испортился, то можно ли его называть древнегреческим?")
Это тоже должно быть в тесте

2019-12-18 01:38 UTC, dkotegov commented on tests/AskPage.py
> +            lambda d: d.find_element_by_xpath('//div[@name="poll_options"]/div[4]/label/div[2]/div/div/div/input')
:(

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +import time
не используется ;)

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.clickLogin()
Это в пейджи

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.checkAlert()
а это в тесты

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.clickAndWaitProfile()
а где ассерты?

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +        self.assertTrue(self.page.checkUrl())
Можно объединить с предыдущим тестом

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +            print('Photo/video upload test:.............PASSED\n')
Дебажных принтов быть не должно

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.press_esc()
Проверок нет

2019-12-18 01:38 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.open_video_upload_form()
Почему 2 раза?

2019-12-18 15:35 UTC, rakhimgaliyev commented on tests/AskTests.py
> +        self.page.quitDriver()
done

2019-12-18 15:35 UTC, rakhimgaliyev commented on tests/AskPage.py
> +        self.driver.find_elements_by_class_name('login-row')[2].find_elements_by_css_selector('*')[5].click()
исправил, теперь поиск по имени

2019-12-18 15:35 UTC, rakhimgaliyev commented on tests/AskPage.py
> +    def checkUrl(self):
исправлено

2019-12-18 15:36 UTC, rakhimgaliyev commented on tests/AskPage.py
> +            # lambda d: d.find_element_by_xpath('//button[@name="submit_btn"]').click()
удалили

2019-12-18 15:36 UTC, rakhimgaliyev commented on tests/AskPage.py
> +        self.setQuestionAdditional(u"Собственно говоря, если греческий салат испортился, то можно ли его называть древнегреческим?")
перенесли

2019-12-18 15:36 UTC, rakhimgaliyev commented on tests/AskTests.py
> +        self.page.clickAndWaitProfile()
Переделал

2019-12-18 15:36 UTC, rakhimgaliyev commented on tests/AskTests.py
> +            print('Photo/video upload test:.............PASSED\n')
убрали все принты

2019-12-18 15:37 UTC, rakhimgaliyev commented on tests/AskTests.py
> +        self.assertTrue(self.page.checkUrl())
объединил

2019-12-18 15:37 UTC, rakhimgaliyev commented on tests/AskTests.py
> +        self.page.press_esc()
Кинули проверку

2019-12-18 15:38 UTC, rakhimgaliyev commented on tests/AskTests.py
> +        self.page.open_video_upload_form()
Потому что кейс такой: проверяется работоспособность кнопок 'загрузить видео' и 'загрузить фото'

2019-12-18 22:07 UTC, dkotegov commented
Все еще падает:
```
d:homework-4 (master) d.kotegov$ python run_tests.py
....E.......
======================================================================
ERROR: test_notEmptyQuestion (tests.AskTests.AskTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskTests.py", line 57, in test_notEmptyQuestion
    self.assertEqual(self.page.getAlertUnderQuestion(),
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskPage.py", line 147, in getAlertUnderQuestion
    alert = self.driver.find_element_by_class_name('z1LfJpugzE39YVXERE-f__0')
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".z1LfJpugzE39YVXERE-f__0"}
  (Session info: chrome=79.0.3945.88)


----------------------------------------------------------------------
Ran 12 tests in 69.716s

FAILED (errors=1)
```

2019-12-18 22:08 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.open_video_upload_form()
Не заменил что названия разные, все ок

2019-12-18 22:18 UTC, dkotegov requested changes

2019-12-18 22:18 UTC, dkotegov commented on tests/AskPage.py
> +        self.driver.find_elements_by_css_selector('*')[0].get_attribute('innerHTML')
Зачем этот find, если дальше он не используется?

2019-12-18 22:18 UTC, dkotegov commented on tests/AskPage.py
> +                self.PROFILE_BUTTON)))[7]
42

2019-12-18 22:18 UTC, dkotegov commented on tests/AskPage.py
> +        buttonChooseAnother[-1].click()
Такой селектор может упасть от малейших изменений на сайте

2019-12-18 22:18 UTC, dkotegov commented on tests/AskPage.py
> +        except:
Плохо перехватывать всё

2019-12-18 22:18 UTC, dkotegov commented on tests/AskPage.py
> +            lambda d: d.find_element_by_xpath('//div[@name="poll_options"]/div[5]/label/div[2]/div/div/div/input')
Я в глубокой печали от таких селекторов :(

2019-12-18 22:18 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.open()
Копипаста, унесите в setUp

2019-12-18 22:42 UTC, dkotegov commented
Обсудили голосом, нужно поправить замечания, селекторы, добавить очистку и добиться того, чтобы тесты проходили

2019-12-19 01:38 UTC, dkotegov commented on tests/AskPage.py
> +        except Exception:
Ну блин!

2019-12-19 01:39 UTC, dkotegov commented on tests/AskPage.py
> +'//div[@name="poll_options"]/div[4]/label/div[2]/div/div/div/input'
:(

2019-12-19 08:27 UTC, rakhimgaliyev commented on tests/AskPage.py
> +        buttonChooseAnother[-1].click()
Нам нужно выбрать категорию 'Другое', он самый последний в списке Категорий. У всех полей в списке одинаковые идентификаторы, а искать по тексту - дорого. Чтобы тест упал, нужно удалить вкладку "Категории"

2019-12-19 16:01 UTC, dkotegov commented on tests/AskPage.py
> +        self.password = "qqaawwss123"
:(

2019-12-19 16:13 UTC, dkotegov commented
Тесты падают
```
d:homework-4 (master) d.kotegov$ python run_tests.py
...EE......
======================================================================
ERROR: test_newQuestionEditTest (tests.AskTests.AskTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskTests.py", line 113, in test_newQuestionEditTest
    self.page.setQuestionTheme(randTitle)
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskPage.py", line 98, in setQuestionTheme
    self.sendText(inputQuestionField, question)
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskPage.py", line 82, in sendText
    webElement, text[:len(text)-1])
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 372, in execute
    data = utils.dump_json(params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/utils.py", line 33, in dump_json
    return json.dumps(json_struct)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 46: unexpected end of data

======================================================================
ERROR: test_notEmptyQuestion (tests.AskTests.AskTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskTests.py", line 61, in test_notEmptyQuestion
    self.assertEqual(self.page.getAlertUnderAdditional(),
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskPage.py", line 87, in getAlertUnderAdditional
    ALERT_ADDITIONAL)) \
  File "/Users/d.kotegov/TPHomeWork/homework-4/tests/AskPage.py", line 78, in waitForElementVisible
    EC.visibility_of_element_located(locator))
  File "/Library/Python/2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:


----------------------------------------------------------------------
Ran 11 tests in 68.550s

FAILED (errors=2)
```

2020-01-05 19:59 UTC, dkotegov requested changes

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +        self.password = 'password_norm'
Где-то умер котёнок

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +            return False
А зачем перехватывать? Пусть падает в этом случае

2020-01-05 19:59 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.can_press_esc()
Проверки должны быть в тестах

2020-01-05 19:59 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.can_press_esc()
И тут

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +        webElement.send_keys(text[len(text)-1])
3 очень странных строчки. Зачем так?

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +    def sameUrl(self, url):
ассерты должны быть в тесте
сделайте метод get_url() и проверку в тесте assertEqual(current_url, expected_url)
а лучше проверять контент

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +    def lofinFormIsVisible(self):
Это тоже внутри теста должно быть

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +                exceptions.TimeoutException) as error:
Что-то вы делаете не так, зачем перехватывать их все?

2020-01-05 19:59 UTC, dkotegov commented on tests/AskTests.py
> +        self.assertTrue(self.page.clickAndWaitProfile())
Это антипаттерн, запустили функцию и если прошла - значит все работает
Но это не так, никаких проверок в этом тесте нет, фича не проверяется

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +    def isAlert(self):
Это тоже

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +                pass
Весь for и try костыль

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +        photo_span.find_element_by_xpath('./..').click()
А если порядок элементов поменяется?

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +    def check_settings_page(self):
И тут

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +    def can_edit_time(self):
И тут

2020-01-05 19:59 UTC, dkotegov commented on tests/AskPage.py
> +    def check_poll_option_correct_add(self):
И тут

2020-01-05 20:00 UTC, dkotegov commented on tests/AskPage.py
> +        self.password = 'SomePasswordHere'
:(

2020-01-05 20:11 UTC, Gel0bmstu commented on tests/AskPage.py
> +            return False
тут не очень понятно, он ведь упадет если false вернет

2020-01-06 09:45 UTC, rakhimgaliyev commented on tests/AskPage.py
> +        webElement.send_keys(text[len(text)-1])
У нас есть тест, где нужно вставить > 3800 символов. Если использовать метод send_keys, то это долго. Если просто вставить строку в атрибут text вебЕлемента, сайт не кидает предупреждение о длинной строке. Скорее всего это из-за того, что там стоит eventListener на keyPressed. Поэтому последний символ мы прописываем методом send_keys.

2020-01-06 09:45 UTC, rakhimgaliyev commented on tests/AskPage.py
> +        webElement.send_keys(text[len(text)-1])
У нас есть тест, где нужно вставить > 3800 символов. Если использовать метод send_keys, то это долго. Если просто вставить строку в атрибут text вебЕлемента, сайт не кидает предупреждение о длинной строке. Скорее всего это из-за того, что там стоит eventListener на keyPressed. Поэтому последний символ мы прописываем методом send_keys.

2020-01-07 23:46 UTC, Gel0bmstu commented
### Добрый вечер. Мы исправили следующие недочеты:
  1. Убраны лишние try-except блоки.
  2. Все проверки перенесены в тесты.
  3. Заменены каскадные XPath'ы.
  4. Убраны логины и пароли из кода (на этот раз без мертвых котят).
  5. Зарефакторили код, все вейты обернули в обертки, прошлись еще раз pycodestyle'ом,
исправили все ексепшины с учетом максимально длтны строки в 120 символов.
  6. Все тесты проходят на chrome/firefox (Ubuntu LTS 19.10 / Arch 4.19.91)

2020-01-08 11:45 UTC, dkotegov commented on tests/AskTests.py
> +        self.assertTrue(self.page.check_edit_profile_section())
Тут не поправили

2020-01-08 11:57 UTC, dkotegov commented on tests/AskTests.py
> +                         u'Поле «Тема вопроса» обязательно для заполнения')
Вот этот ассерт падает, потому что предыдущая строчка не отрабатывает

2020-01-08 11:59 UTC, dkotegov commented on tests/AskPage.py
> +    def check_video_upload_section(self):
Переименуйте

2020-01-08 12:00 UTC, dkotegov commented on tests/AskPage.py
> +        try:
Не надо перехватывать, пусть падает, если не получилось

2020-01-08 12:02 UTC, dkotegov commented on tests/AskTests.py
> +        self.assertTrue(self.page.check_alert_messege())
Лучше проверять содержимое

2020-01-08 12:02 UTC, dkotegov commented on tests/AskTests.py
> +        self.assertTrue(self.page.check_alert_messege())
И тут

2020-01-08 12:02 UTC, dkotegov commented on tests/AskTests.py
> +        self.page.check_poll_option_correct_add()
Антипаттерн

2020-01-08 19:19 UTC, dkotegov commented on tests/AskPage.py
> +        # self.password = os.environ['PASSWORD']
?

2020-01-08 19:21 UTC, dkotegov commented on tests/AskPage.py
> +        # )
?

2020-01-08 19:21 UTC, dkotegov commented on tests/AskPage.py
> +        # self._wait_visibility((By.CLASS_NAME, QUESTION_EDIT_SECTION))
?

2020-01-08 19:22 UTC, dkotegov commented on tests/AskTests.py
> +        self.assertIsNotNone(self.page.get_edit_profile_section())
А тесте все еще ничего не проверяется

2020-01-08 19:22 UTC, dkotegov commented on tests/AskTests.py
> +        self.assertIsNotNone(self.page.get_edit_question_section())
И тут

2020-01-09 00:55 UTC, dkotegov commented on tests/AskPage.py
> +        except exceptions.StaleElementReferenceException:
Костыль

2020-01-09 00:56 UTC, dkotegov commented
Ладно

2020-01-09 00:56 UTC, closed without merging