git-reset__--hard
dkotegov/homework-4 pull request #77
Opened 2019-11-18 18:04 UTC by Lunex08

Векшин Роман
Захаров Дмитрий
Ражев Михаил

2019-12-17 23:37 UTC, dkotegov commented
Тесты падают:
```
d:homework-4 (master) d.kotegov$ python run_tests.py
..........cant find element: //div[@class="group__header" and text()="Неразобранное"]/..//div[@class="group__items"]/div[@class="group__item"]//div[@title="Редактировать задачу"]
E.......
======================================================================
ERROR: test_task_date_changing (__main__.TestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_tests.py", line 142, in test_task_date_changing
    set_date_last_created_task_without_date(self, tomorrow)
  File "/Users/d.kotegov/TPHomeWork/homework-4/steps/calendar.py", line 264, in set_date_last_created_task_without_date
    tasks_wrapper.open_last_created_task_settings(task_list_title)
  File "/Users/d.kotegov/TPHomeWork/homework-4/pages/calendar.py", line 264, in open_last_created_task_settings
    webdriver.ActionChains(self.driver).click(self.wait_for_visible(LAST_CREATED_TASK_SETTINGS_BUTTON)).perform()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/action_chains.py", line 102, in click
    self.move_to_element(on_element)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/action_chains.py", line 273, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/actions/pointer_actions.py", line 42, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

----------------------------------------------------------------------
Ran 18 tests in 168.326s

FAILED (errors=1)
```

2019-12-18 00:40 UTC, dkotegov requested changes

2019-12-18 00:40 UTC, dkotegov commented on pages/default.py
> +            print('cant find element: ' + xpath)
Дебажных принтов быть не должно

2019-12-18 00:40 UTC, dkotegov commented on pages/auth.py
> +from default import *
Плохо импортировать *
Получите головную боль при дебаге

2019-12-18 00:40 UTC, dkotegov commented on pages/calendar.py
> +        time_format_len = 5
Тестовые данные должны быть в тестах

2019-12-18 00:40 UTC, dkotegov commented on pages/calendar.py
> +            start.send_keys(Keys.BACK_SPACE)
clear()

2019-12-18 00:40 UTC, dkotegov commented on steps/calendar.py
> +    except NoSuchElementException:
А зачем тут find который всегда будет рейзить NoSuchElementException?
wait_for_disappear должен падать, если действие не удалось
Здесь можно оставить только return

2019-12-18 00:40 UTC, dkotegov commented on pages/calendar.py
> +            if i <= max_workdays:
Кажется это можно делать за один проход выше

2019-12-18 00:40 UTC, dkotegov commented on pages/calendar.py
> +    def change_to_zero_workdays(self):
А этот метод можно объединить с предыдущим, а количество дней вынести в параметры

2019-12-18 00:40 UTC, dkotegov commented on pages/calendar.py
> +        self.driver.find_element_by_xpath(self.SETTINGS_REMINDERS_BUTTON).click()
3 раза ищется элемент вместо 1

2019-12-18 00:40 UTC, dkotegov commented on pages/calendar.py
> +    def change_to_zero_reminders(self):
И тут

2019-12-18 00:40 UTC, dkotegov commented on pages/calendar.py
> +        sound = self.driver.find_element_by_xpath(self.REMINDERS_SOUND)
И тут

2019-12-18 00:40 UTC, dkotegov commented on run_tests.py
> +        result = set_create_event_w_attendees(self)
Это антипаттерн, перенесите в сам тест

2019-12-18 00:40 UTC, dkotegov commented on run_tests.py
> +        is_saved_successfully = True
Уберите :(

2019-12-18 00:40 UTC, dkotegov commented on run_tests.py
> +        self.assertEqual(is_saved_successfully, result)
assertTrue

2019-12-18 00:40 UTC, dkotegov commented on run_tests.py
> +    unittest.main()
Сделайте отдельный файл с тестами

2019-12-18 00:40 UTC, dkotegov commented on steps/auth.py
> +    auth_form.submit()
Так у вас же есть  pages/auth.py  ;)

2019-12-19 14:41 UTC, BrBrRoman commented on run_tests.py
> +        result = set_create_event_w_attendees(self)
Done

2019-12-19 14:42 UTC, BrBrRoman commented on run_tests.py
> +        is_saved_successfully = True
Done

2019-12-19 14:42 UTC, BrBrRoman commented on run_tests.py
> +        self.assertEqual(is_saved_successfully, result)
Done

2020-04-01 21:05 UTC, closed without merging